(function(){
'use strict';
const $=id=>document.getElementById(id);
const participationId=new URLSearchParams(location.search).get('participation');
let participation=null,meta=null,decks=[],candidates=[],analysis=null,activeField=null,baselineField=[],field=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[c]));
const pct=v=>`${(Number(v||0)*100).toFixed(1)}%`;
function toast(message){const el=$('toast');el.textContent=message;el.classList.remove('hidden');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.add('hidden'),2200)}
function saveLabel(text){$('saveState').textContent=text}
function eventName(){const s=participation?.eventSnapshot||{};return s.name||s.venue||s.city||'Event'}
function eventKind(){const s=participation?.eventSnapshot||{};const majorTypes=new Set(['Regional','Special Championship','International','World Championships']);return s.scope==='major'||majorTypes.has(s.type)?'major':'local'}
function baselineName(){return eventKind()==='major'?'Major':'Local'}
function cleanField(rows){return window.SavedMetas.cleanField(rows)}
function cloneField(rows){return cleanField(rows).map(row=>({...row}))}
function loadParticipation(){participation=window.PTCGStorage?.getParticipation?.(participationId);if(!participation)throw new Error('This event participation could not be found.');if(participation.attendanceStatus!=='attending')throw new Error('Event Prep opens from an Attending event. Mark this event as Attending first.')}
function renderEvent(){const s=participation.eventSnapshot||{};$('eventTitle').textContent=eventName();$('headerEvent').textContent=eventName();const bits=[];if(s.startDate)bits.push(new Date(`${s.startDate}T12:00:00`).toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short',year:'numeric'}));if(s.venue)bits.push(s.venue);else if(s.city)bits.push(s.city);$('eventMeta').textContent=bits.join(' · ')||'Attending event';$('baselineLabel').textContent=baselineName()}
async function loadMeta(){const core=await window.MetaRelease.ready();if(!core)throw new Error('Meta release is unavailable');const [onlineEvidence,irlEvidence]=await Promise.all([window.MetaRelease.load('onlineMatchups'),window.MetaRelease.load('irlMatchups')]);const manifest=window.MetaRelease.manifest();const defaults=window.PTCGRecommendation.DEFAULTS;const online=core?.online?.scopes?.[defaults.onlineScope]||{};const map=new Map();const add=row=>{if(!window.PTCGMetaField.isUsableName(row?.name))return;const prior=map.get(row.name)||{name:row.name,entries:0,count:0};prior.entries+=Number(row.entries||0);prior.count=prior.entries;map.set(row.name,prior)};(online.decks||[]).forEach(add);for(const event of core?.irl?.events||[])for(const row of event.decks||event.archetypes||[])add(row);const currentField=window.PTCGMetaBlend.currentFromCore(core);const onlineMatchups=onlineEvidence?.scopes?.[defaults.onlineScope]||{overview:{},matchups:[]};meta={source:'ptcg-meta-release',format:manifest?.format||core.format,generatedAt:core?.online?.generatedAt,core,currentField,overview:{tournaments:Number(online.overview?.events||0)+(core?.irl?.events||[]).length,players:online.overview?.entries||0,matches:Number(onlineMatchups.overview?.matches||0)+Number(irlEvidence?.overview?.matches||0)},decks:[...map.values()],evidence:{online:onlineMatchups.matchups||[],irl:irlEvidence?.matchups||[]}};if(!Array.isArray(meta.decks)||!Array.isArray(meta.evidence.online)||!Array.isArray(meta.evidence.irl))throw new Error('Meta evidence is invalid')}
function suggestedField(){return window.PTCGMetaField.selectCoverage(meta?.currentField?.rows||[],0.9).rows.map(row=>({name:row.name,share:row.share}))}
function matchingSavedField(){const saved=window.SavedMetas.list();const priorId=participation?.prep?.baselineExpectedFieldId||participation?.prep?.expectedFieldId;const prior=priorId?window.SavedMetas.get(priorId):null;if(prior)return prior;const matcher=eventKind()==='major'?/(major|regional)/i:/local/i;return saved.find(row=>matcher.test(row.name))||null}
function provenanceFor(record){return record?.provenance||{type:'meta-field',identity:'exact-variant',source:'blend',format:meta?.format||'TEF-PBL',generatedAt:meta?.generatedAt||null,scope:'shared-current-blend',onlineScope:meta?.currentField?.onlineScope||'since-major',irlScope:meta?.currentField?.irlScope||'latest-weekend',weights:meta?.currentField?.weights||null,tournaments:meta?.overview?.tournaments||null,players:meta?.overview?.players||null}}
function ensureBaselineRecord(){if(activeField)return activeField;const record=window.SavedMetas.save(baselineName(),baselineField,meta?.format||'TEF-PBL',provenanceFor(null));if(record){activeField=record;baselineField=cloneField(record.field)}return record}
function fieldSnapshot(record){return {expectedFieldId:record?.id||null,baselineExpectedFieldId:record?.id||null,name:`${eventName()} Expected Field`,field:cloneField(field),baselineField:cloneField(baselineField),format:record?.format||meta?.format||'',provenance:provenanceFor(record),note:$('fieldNote').value.trim()||null,capturedAt:new Date().toISOString()}}
function updateParticipation(mutator){participation=window.PTCGStorage.updateParticipation(participation.id,row=>{mutator(row);row.prep=row.prep||{id:`prep-${Date.now().toString(36)}`,participationId:row.id,createdAt:new Date().toISOString()};row.prep.updatedAt=new Date().toISOString();return row});saveLabel('Saved');return participation}
function saveEventField(){const record=ensureBaselineRecord();if(!record)return null;const snapshot=fieldSnapshot(record);updateParticipation(row=>{row.prep=row.prep||{};row.prep.baselineExpectedFieldId=record.id;row.prep.expectedFieldId=record.id;row.prep.expectedFieldSnapshot=snapshot;row.prep.eventFieldNote=snapshot.note});renderFieldSelect();renderFieldSummary();renderCandidates();return snapshot}
function renderFieldSelect(){const saved=window.SavedMetas.list();const suggested=`Suggested ${baselineName()} baseline`;const selected=activeField?.id||'';$('savedFieldSelect').innerHTML=`<option value="">${esc(suggested)}</option>${saved.map(row=>`<option value="${esc(row.id)}" ${selected===row.id?'selected':''}>${esc(row.name)}</option>`).join('')}`}
function renderFieldSummary(){const snapshot=participation?.prep?.expectedFieldSnapshot;const isSaved=snapshot?.field?.length;const source=activeField?.name||`Suggested ${baselineName()}`;$('fieldStatus').textContent=isSaved?'Set for event':activeField?'Using saved field':'Suggested';const provenance=provenanceFor(activeField);const gen=provenance.generatedAt?new Date(provenance.generatedAt).toLocaleDateString('en-GB',{day:'numeric',month:'short'}):'date unavailable';$('fieldEvidence').textContent=`${source} · ${provenance.source||'Meta evidence'} · ${gen}`;const visible=field.slice(0,8);$('fieldSummary').innerHTML=visible.map(row=>`<div class="field-chip"><span>${esc(row.name)}</span><b>${pct(row.share)}</b></div>`).join('')+(field.length>8?`<div class="field-more">+${field.length-8} more</div>`:'');renderAdjustRows()}
function renderAdjustRows(){$('fieldAdjustRows').innerHTML=field.slice(0,12).map((row,i)=>`<label class="adjust-row"><span>${esc(row.name)}</span><span class="adjust-value"><input data-field-index="${i}" type="number" min="0" max="100" step="0.5" value="${(row.share*100).toFixed(1)}"><b>%</b></span></label>`).join('');$('fieldAdjustRows').querySelectorAll('input').forEach(input=>input.addEventListener('change',()=>{const i=Number(input.dataset.fieldIndex);field[i].share=Math.max(0,Number(input.value||0))/100;field=cleanField(field);renderFieldSummary();saveLabel('Unsaved event adjustment')}))}
function useSavedField(){const id=$('savedFieldSelect').value;activeField=id?window.SavedMetas.get(id):null;baselineField=activeField?cloneField(activeField.field):suggestedField();field=cloneField(baselineField);$('fieldNote').value='';renderFieldSummary();renderCandidates();saveLabel('Baseline selected')}
function resetAdjustment(){field=cloneField(baselineField);$('fieldNote').value='';renderFieldSummary();saveLabel('Baseline restored')}
function candidateState(name){const state=participation?.prep?.candidates?.[name];const funnel=state?.funnelState||'Considering';return funnel==='Leading choice'?'leading':funnel==='Dropped'?'no':'maybe'}
function buildCandidates(){const owned=new Set(decks.map(d=>d.archetype).filter(Boolean));analysis=window.PTCGRecommendation.analyse({fieldRows:field,candidates:meta?.decks||[],evidence:meta?.evidence||{},matchupSource:'combined'});candidates=analysis.ranked.slice(0,4).map(row=>({...row,score:row.expectedWR/100,games:row.decisiveGames,owned:owned.has(row.name)}))}
function persistCandidate(name,state){const funnelState=state==='leading'?'Leading choice':state==='no'?'Dropped':'Considering';updateParticipation(row=>{row.prep=row.prep||{};row.prep.candidates=row.prep.candidates||{};if(state==='leading'){for(const key of Object.keys(row.prep.candidates))if(key!==name&&row.prep.candidates[key].funnelState==='Leading choice')row.prep.candidates[key].funnelState='Considering'}row.prep.candidates[name]={...(row.prep.candidates[name]||{}),funnelState,updatedAt:new Date().toISOString()}});renderCandidates();renderPlan()}
function renderCandidates(){buildCandidates();const stateLabel={strong:'Strong recommendation',close:'Close call',leading:'Best current fit',promising:'Promising, weak evidence',insufficient:'Insufficient evidence'}[analysis.state];$('candidateEvidence').textContent=`${stateLabel} · shared WSIP model · Online 30 days + all-format IRL H2H.`;if(!candidates.length){$('candidateRows').innerHTML='<div class="prep-empty">Not enough coverage and sample quality for a useful shortlist.</div>';return}$('candidateRows').innerHTML=candidates.map(c=>{const state=candidateState(c.name);return `<article class="candidate-card"><div class="candidate-main"><div class="candidate-title"><strong>${esc(c.name)}${c.owned?'<small>Your deck</small>':''}</strong><span>≈${Math.round(c.expectedWR)}%</span></div><div class="candidate-evidence">${pct(c.coverage)} field coverage · ${pct(c.evidenceQuality)} sample quality · ${esc(c.evidenceLabel)}</div><div class="candidate-buttons"><button type="button" data-candidate="${esc(c.name)}" data-state="leading" class="${state==='leading'?'active':''}">Leading</button><button type="button" data-candidate="${esc(c.name)}" data-state="maybe" class="${state==='maybe'?'active':''}">Maybe</button><button type="button" data-candidate="${esc(c.name)}" data-state="no" class="${state==='no'?'active':''}">No</button></div></div></article>`}).join('');$('candidateRows').querySelectorAll('[data-candidate]').forEach(button=>button.addEventListener('click',()=>persistCandidate(button.dataset.candidate,button.dataset.state)))}
async function loadDecks(){decks=await window.PTCGDeckStore.all();renderCandidates();renderPlan()}
function selectedDeck(){return decks.find(d=>d.id===$('deckSelect').value)||null}
function leadingCandidate(){const rows=participation?.prep?.candidates||{};return Object.entries(rows).find(([,s])=>s.funnelState==='Leading choice')?.[0]||null}
function plannedDetails(){const planned=participation?.plannedDeckRef;if(!planned)return null;const deck=decks.find(d=>d.id===planned.deckId);const version=deck&&window.PTCGDeckStore.getVersion(deck,planned.deckVersionId);return deck&&version?{deck,version}:null}
function renderPlan(){const leading=leadingCandidate();const planned=plannedDetails();$('planStatus').textContent=planned?'Planned':leading?'Leading selected':'Not chosen';$('planHint').textContent=leading&&!planned?`${leading} is your leading option.`:'';if(planned){$('plannedSummary').classList.remove('hidden');$('planEditor').classList.add('hidden');$('plannedSummary').innerHTML=`<div><strong>${esc(planned.deck.name)} · ${esc(planned.version.label||`V${planned.version.ordinal||1}`)}</strong>${planned.deck.archetype?`<span>${esc(planned.deck.archetype)}</span>`:''}</div><button id="changePlan" type="button" class="secondary-button">Change</button>`;$('changePlan').addEventListener('click',()=>{$('plannedSummary').classList.add('hidden');$('planEditor').classList.remove('hidden')})}else{$('plannedSummary').classList.add('hidden');$('planEditor').classList.remove('hidden')}
 const sorted=[...decks].sort((a,b)=>{const am=leading&&a.archetype===leading?0:1,bm=leading&&b.archetype===leading?0:1;return am-bm||(b.updatedAt||0)-(a.updatedAt||0)});const prior=$('deckSelect').value||participation?.plannedDeckRef?.deckId||'';$('deckSelect').innerHTML=`<option value="">Choose a personal deck</option>${sorted.map(d=>`<option value="${esc(d.id)}">${esc(d.name)}${d.archetype?` · ${esc(d.archetype)}`:''}</option>`).join('')}`;if(sorted.some(d=>d.id===prior))$('deckSelect').value=prior;renderVersions()}
function renderVersions(){const deck=selectedDeck();const planned=participation?.plannedDeckRef||null;const versions=deck?.versions||[];const plannedVersionId=planned&&deck&&planned.deckId===deck.id?planned.deckVersionId:'';const prior=$('versionSelect').value||plannedVersionId||deck?.currentVersionId||'';$('versionSelect').innerHTML=`<option value="">Choose an exact version</option>${versions.slice().reverse().map(v=>`<option value="${esc(v.id)}">${esc(v.label||`V${v.ordinal||1}`)}${v.name?` · ${esc(v.name)}`:''}</option>`).join('')}`;if(versions.some(v=>v.id===prior))$('versionSelect').value=prior;const version=versions.find(v=>v.id===$('versionSelect').value);$('versionMeta').textContent=version?(version.name||version.listHash||'Saved version'):(deck&&!versions.length?'This deck has no saved version yet.':'')}
function savePlan(){const deck=selectedDeck();const version=deck&&window.PTCGDeckStore.getVersion(deck,$('versionSelect').value);if(!deck||!version||!version.listHash){toast('Choose a saved DeckVersion first');return}updateParticipation(row=>{row.plannedDeckRef={deckId:deck.id,deckVersionId:version.id,listHash:version.listHash,plannedAt:new Date().toISOString()};row.prep=row.prep||{};row.prep.plannedArchetype=deck.archetype||null});renderPlan();toast('Event plan saved')}
function bind(){$('savedFieldSelect').addEventListener('change',useSavedField);$('looksRight').addEventListener('click',()=>{if(saveEventField())toast('Field set for this event')});$('toggleAdjust').addEventListener('click',()=>{$('adjustPanel').classList.toggle('hidden')});$('resetAdjust').addEventListener('click',resetAdjustment);$('saveEventField').addEventListener('click',()=>{if(saveEventField()){toast('Event adjustment saved');$('adjustPanel').classList.add('hidden')}});$('deckSelect').addEventListener('change',renderVersions);$('versionSelect').addEventListener('change',renderVersions);$('savePlan').addEventListener('click',savePlan);window.addEventListener('savedmetas:updated',renderFieldSelect)}
async function init(){try{loadParticipation();renderEvent();await Promise.all([loadMeta(),window.PTCGDeckStore.open()]);activeField=matchingSavedField();const snap=participation?.prep?.expectedFieldSnapshot;baselineField=snap?.baselineField?.length?cloneField(snap.baselineField):activeField?.field?.length?cloneField(activeField.field):suggestedField();field=snap?.field?.length?cloneField(snap.field):cloneField(baselineField);$('fieldNote').value=participation?.prep?.eventFieldNote||snap?.note||'';renderFieldSelect();renderFieldSummary();await loadDecks();bind();$('workspace').classList.remove('hidden');saveLabel('Saved')}catch(error){console.error(error);$('fatal').textContent=error.message;$('fatal').classList.remove('hidden');saveLabel('Unavailable')}}
init();
})();
