(function(){
'use strict';
const $=id=>document.getElementById(id);
const participationId=new URLSearchParams(location.search).get('participation');
let participation=null,meta=null,field=[],activeField=null,decks=[],candidates=[];
const reactions=['Interested','Comfortable','Practise more','Not for me'];
const funnelStates=['Considering','Leading choice','Chosen','Dropped'];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const pct=v=>`${(Number(v||0)*100).toFixed(1)}%`;
function toast(message){const el=$('toast');el.textContent=message;el.classList.remove('hidden');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.add('hidden'),2200)}
function saveLabel(text){$('saveState').textContent=text}
function eventName(){const s=participation?.eventSnapshot||{};return s.name||s.venue||s.city||'Event'}
function fieldName(){const s=participation?.eventSnapshot||{};const date=s.startDate?new Date(`${s.startDate}T12:00:00`).toLocaleDateString('en-GB',{day:'numeric',month:'short'}):'';return `${eventName()}${date?` · ${date}`:''} Expected Field`}
function cleanField(rows){return window.SavedMetas.cleanField(rows)}
function loadParticipation(){participation=window.PTCGStorage?.getParticipation?.(participationId);if(!participation)throw new Error('This event participation could not be found.');if(participation.attendanceStatus!=='attending')throw new Error('Event Prep opens from an Attending event. Mark this event as Attending first.')}
function renderEvent(){const s=participation.eventSnapshot||{};$('eventTitle').textContent=eventName();$('headerEvent').textContent=eventName();const bits=[];if(s.startDate)bits.push(new Date(`${s.startDate}T12:00:00`).toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short',year:'numeric'}));if(s.venue)bits.push(s.venue);else if(s.city)bits.push(s.city);$('eventMeta').textContent=bits.join(' · ')||'Attending event'}
async function loadMeta(){const response=await fetch('../../data/meta/decks/TEF-PBL.json');if(!response.ok)throw new Error(`Meta evidence unavailable (${response.status})`);const payload=await response.json();if(!Array.isArray(payload.decks)||!Array.isArray(payload.matchups))throw new Error('Meta evidence is invalid');meta=payload}
function suggestedField(){const rows=(meta?.decks||[]).filter(d=>d?.name&&Number(d.share)>0).sort((a,b)=>Number(b.share)-Number(a.share));let cumulative=0;const picked=[];for(const row of rows){if(cumulative>=90&&picked.length)break;picked.push({name:row.name,share:Number(row.share)/100});cumulative+=Number(row.share)}return cleanField(picked)}
function fieldSnapshot(record){return {expectedFieldId:record.id,name:record.name,field:cleanField(record.field),format:record.format||meta?.format||'',provenance:record.provenance||null,capturedAt:new Date().toISOString()}}
function updateParticipation(mutator){participation=window.PTCGStorage.updateParticipation(participation.id,row=>{mutator(row);row.prep=row.prep||{id:`prep-${Date.now().toString(36)}`,participationId:row.id,createdAt:new Date().toISOString()};row.prep.updatedAt=new Date().toISOString();return row});saveLabel('Saved');return participation}
function saveExpectedField(){const provenance=activeField?.provenance||{type:'meta-aggregate',source:meta?.source||'limitless-decks',format:meta?.format||'TEF-PBL',generatedAt:meta?.generatedAt||null,scope:'all-format',tournaments:meta?.overview?.tournaments||null,players:meta?.overview?.players||null};const record=window.SavedMetas.save(activeField?.name||fieldName(),field,meta?.format||'TEF-PBL',provenance);if(!record)return null;activeField=record;field=cleanField(record.field);updateParticipation(row=>{row.prep=row.prep||{};row.prep.expectedFieldId=record.id;row.prep.expectedFieldSnapshot=fieldSnapshot(record)});renderFieldSelect();renderField();renderCandidates();return record}
function renderFieldSelect(){const saved=window.SavedMetas.list();$('savedFieldSelect').innerHTML=`<option value="">Suggested Meta baseline</option>${saved.map(row=>`<option value="${esc(row.id)}" ${activeField?.id===row.id?'selected':''}>${esc(row.name)}</option>`).join('')}`}
function renderField(){const snapshot=participation?.prep?.expectedFieldSnapshot;$('fieldStatus').textContent=snapshot&&activeField?.id===snapshot.expectedFieldId?'Locked snapshot':activeField?'Reusable field':'Suggested';const provenance=activeField?.provenance||{source:meta?.source||'limitless-decks',generatedAt:meta?.generatedAt,scope:'all-format',tournaments:meta?.overview?.tournaments,players:meta?.overview?.players};const gen=provenance?.generatedAt?new Date(provenance.generatedAt).toLocaleDateString('en-GB',{day:'numeric',month:'short'}):'date unavailable';$('fieldEvidence').textContent=`${provenance?.source||'Meta evidence'} · ${provenance?.scope||'saved field'} · ${provenance?.tournaments?`${Number(provenance.tournaments).toLocaleString()} events · `:''}${provenance?.players?`${Number(provenance.players).toLocaleString()} entries · `:''}${gen}`;$('fieldRows').innerHTML=field.map((row,i)=>`<div class="field-row"><span>${esc(row.name)}</span><label><input data-field-index="${i}" type="number" min="0" max="100" step="0.1" value="${(row.share*100).toFixed(1)}"><b>%</b></label></div>`).join('');$('fieldRows').querySelectorAll('input').forEach(input=>input.addEventListener('change',()=>{const i=Number(input.dataset.fieldIndex);field[i].share=Math.max(0,Number(input.value||0))/100;field=cleanField(field);activeField=activeField?{...activeField,field}:null;renderField();renderCandidates();saveLabel('Unsaved field changes')}))}
function matchupMap(){return new Map((meta?.matchups||[]).map(row=>[`${row.a}|||${row.b}`,row]))}
function candidateScore(deck,map){let weighted=0,covered=0,games=0;for(const opponent of field){const m=map.get(`${deck.name}|||${opponent.name}`);const decisive=Number(m?.wins||0)+Number(m?.losses||0);if(!m||decisive<10)continue;weighted+=(Number(m.wins||0)/decisive)*opponent.share;covered+=opponent.share;games+=Number(m.games||decisive+Number(m.ties||0))}return {score:covered?weighted/covered:null,coverage:covered,games}}
function candidateState(name){return participation?.prep?.candidates?.[name]||{funnelState:'Considering',reaction:null}}
function buildCandidates(){const map=matchupMap();candidates=(meta?.decks||[]).filter(d=>Number(d.count||0)>=100).map(d=>({...d,...candidateScore(d,map)})).filter(d=>d.score!==null&&d.coverage>=0.45).sort((a,b)=>b.score-a.score||b.coverage-a.coverage).slice(0,4)}
function persistCandidate(name,patch){updateParticipation(row=>{row.prep=row.prep||{};row.prep.candidates=row.prep.candidates||{};const existing=row.prep.candidates[name]||{funnelState:'Considering',reaction:null};row.prep.candidates[name]={...existing,...patch,updatedAt:new Date().toISOString()};if(patch.funnelState==='Chosen'){for(const key of Object.keys(row.prep.candidates))if(key!==name&&row.prep.candidates[key].funnelState==='Chosen')row.prep.candidates[key].funnelState='Considering'}});renderCandidates();renderPlan()}
function renderCandidates(){buildCandidates();const evidence=meta?.overview||{};$('candidateEvidence').textContent=`Estimated win rate into the selected field · exact-variant all-event matchup evidence · ${Number(evidence.matches||0).toLocaleString()} games in source cache.`;if(!candidates.length){$('candidateRows').innerHTML='<div class="prep-empty">Not enough matchup coverage to make a reliable candidate shortlist.</div>';return}$('candidateRows').innerHTML=candidates.map((c,i)=>{const state=candidateState(c.name);return `<article class="candidate-card"><div class="candidate-rank">${i+1}</div><div class="candidate-main"><div class="candidate-title"><strong>${esc(c.name)}</strong><span>${pct(c.score)}</span></div><div class="candidate-evidence">${pct(c.coverage)} field coverage · ${Number(c.games||0).toLocaleString()} evidence games</div><div class="candidate-controls"><select data-funnel="${esc(c.name)}">${funnelStates.map(x=>`<option ${state.funnelState===x?'selected':''}>${x}</option>`).join('')}</select><select data-reaction="${esc(c.name)}"><option value="">Reaction</option>${reactions.map(x=>`<option ${state.reaction===x?'selected':''}>${x}</option>`).join('')}</select></div></div></article>`}).join('');$('candidateRows').querySelectorAll('[data-funnel]').forEach(el=>el.addEventListener('change',()=>persistCandidate(el.dataset.funnel,{funnelState:el.value})));$('candidateRows').querySelectorAll('[data-reaction]').forEach(el=>el.addEventListener('change',()=>persistCandidate(el.dataset.reaction,{reaction:el.value||null})))}
async function loadDecks(){decks=await window.PTCGDeckStore.all();renderPlan()}
function selectedDeck(){return decks.find(d=>d.id===$('deckSelect').value)||null}
function renderPlan(){const savedCandidates=participation?.prep?.candidates||{};const chosen=Object.entries(savedCandidates).find(([,s])=>s.funnelState==='Chosen')?.[0]||Object.entries(savedCandidates).find(([,s])=>s.funnelState==='Leading choice')?.[0]||null;const planned=participation?.plannedDeckRef||null;$('planStatus').textContent=planned?'Planned':chosen?'Candidate chosen':'Not chosen';const sorted=[...decks].sort((a,b)=>{const am=chosen&&a.archetype===chosen?0:1,bm=chosen&&b.archetype===chosen?0:1;return am-bm||(b.updatedAt||0)-(a.updatedAt||0)});const prior=$('deckSelect').value||planned?.deckId||'';$('deckSelect').innerHTML=`<option value="">Choose a personal deck</option>${sorted.map(d=>`<option value="${esc(d.id)}">${esc(d.name)}${d.archetype?` · ${esc(d.archetype)}`:''}</option>`).join('')}`;if(sorted.some(d=>d.id===prior))$('deckSelect').value=prior;renderVersions()}
function renderVersions(){const deck=selectedDeck();const planned=participation?.plannedDeckRef||null;const versions=deck?.versions||[];const plannedVersionId=planned&&deck&&planned.deckId===deck.id?planned.deckVersionId:'';const prior=$('versionSelect').value||plannedVersionId||deck?.currentVersionId||'';$('versionSelect').innerHTML=`<option value="">Choose an exact version</option>${versions.slice().reverse().map(v=>`<option value="${esc(v.id)}">${esc(v.label||`V${v.ordinal||1}`)}${v.name?` · ${esc(v.name)}`:''}</option>`).join('')}`;if(versions.some(v=>v.id===prior))$('versionSelect').value=prior;const version=versions.find(v=>v.id===$('versionSelect').value);$('versionMeta').innerHTML=version?`<strong>${esc(deck.name)} · ${esc(version.label||'Version')}</strong><span>${esc(version.listHash||'Hash unavailable')}</span>`:(deck&&!versions.length?'<span>This deck has no saved DeckVersion yet. Open it in Decks and save a version before planning it.</span>':'')}
function savePlan(){const deck=selectedDeck();const version=deck&&window.PTCGDeckStore.getVersion(deck,$('versionSelect').value);if(!deck||!version||!version.listHash){toast('Choose a saved DeckVersion first');return}updateParticipation(row=>{row.plannedDeckRef={deckId:deck.id,deckVersionId:version.id,listHash:version.listHash,plannedAt:new Date().toISOString()};row.prep=row.prep||{};row.prep.plannedArchetype=deck.archetype||null});renderPlan();toast('Planned DeckVersion saved')}
function useSaved(){const id=$('savedFieldSelect').value;if(!id){activeField=null;field=suggestedField();renderField();renderCandidates();return}const record=window.SavedMetas.get(id);if(!record)return;activeField=record;field=cleanField(record.field);renderField();renderCandidates();saveLabel('Field selected · not yet snapshotted')}
function bind(){$('useSavedField').addEventListener('click',useSaved);$('looksRight').addEventListener('click',()=>{if(saveExpectedField())toast('Expected Field saved and snapshotted')});$('toggleReview').addEventListener('click',()=>$('reviewPanel').classList.toggle('hidden'));$('saveField').addEventListener('click',()=>{if(saveExpectedField())toast('Reusable Expected Field updated')});$('deckSelect').addEventListener('change',renderVersions);$('versionSelect').addEventListener('change',renderVersions);$('savePlan').addEventListener('click',savePlan);window.addEventListener('savedmetas:updated',renderFieldSelect)}
async function init(){try{loadParticipation();renderEvent();await Promise.all([loadMeta(),window.PTCGDeckStore.open()]);const savedId=participation?.prep?.expectedFieldId;activeField=savedId?window.SavedMetas.get(savedId):null;const snap=participation?.prep?.expectedFieldSnapshot;field=snap?.field?.length?cleanField(snap.field):activeField?.field?.length?cleanField(activeField.field):suggestedField();renderFieldSelect();renderField();renderCandidates();await loadDecks();bind();$('workspace').classList.remove('hidden');saveLabel('Saved')}catch(error){console.error(error);$('fatal').textContent=error.message;$('fatal').classList.remove('hidden');saveLabel('Unavailable')}}
init();
})();