(function(){
'use strict';
const $=id=>document.getElementById(id);
let assetsLoaded=false,assetsLoading=null;
function loadScript(src){return new Promise((resolve,reject)=>{const existing=document.querySelector(`script[data-season-asset="${src}"]`);if(existing){if(existing.dataset.loaded==='1')return resolve();existing.addEventListener('load',resolve,{once:true});existing.addEventListener('error',reject,{once:true});return}const script=document.createElement('script');script.src=src;script.dataset.seasonAsset=src;script.addEventListener('load',()=>{script.dataset.loaded='1';resolve()},{once:true});script.addEventListener('error',reject,{once:true});document.body.appendChild(script)})}
function ensureStyle(){if(document.querySelector('link[data-season-style]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href='./season.css?v=2';link.dataset.seasonStyle='1';document.head.appendChild(link)}
function inject(){if($('seasonInlinePanel'))return;const tabs=document.querySelector('.event-view-tabs');if(!tabs)return;const prior=tabs.querySelector('[data-season-link]');const button=document.createElement('button');button.id='seasonTab';button.type='button';button.textContent='Season';button.setAttribute('aria-selected','false');button.setAttribute('aria-label','Competitive season record');if(prior)prior.replaceWith(button);else tabs.appendChild(button);
const panel=document.createElement('section');panel.id='seasonInlinePanel';panel.className='season-inline-panel hidden';panel.innerHTML=`<div class="season-shell"><header class="season-head season-head-compact"><h2>2027 Season</h2><span id="seasonTitle" class="hidden" aria-hidden="true"></span><span id="rulesPill" class="hidden" aria-hidden="true"></span></header><section class="season-score app-card" aria-labelledby="countingLabel"><div class="season-score-main"><small id="countingLabel">Counting CP</small><strong id="countingCP">0</strong></div><div class="season-score-secondary"><div><small>Raw CP</small><strong id="rawCP">0</strong></div><div><small>Eligible events</small><strong id="eligibleEvents">0</strong></div><div><small>Completed</small><strong id="completedEvents">0</strong></div></div></section><section id="bflSection" class="season-section hidden"><div class="season-section-head"><div><h2>Best Finish Limits</h2><p>Only your highest-point finishes count in each bucket.</p></div></div><div id="bflSummary" class="bfl-grid"></div></section><section class="season-section"><div class="season-section-head"><div><h2>Results</h2><p id="resultsHint">Completed Championship Series events this season.</p></div></div><div id="seasonResults" class="season-results"></div><div id="seasonEmpty" class="app-card app-empty hidden">No completed Championship Series results yet.</div></section></div>`;tabs.insertAdjacentElement('afterend',panel);
if(!$('resultBackdrop')){const backdrop=document.createElement('div');backdrop.id='resultBackdrop';backdrop.className='season-backdrop hidden';backdrop.setAttribute('aria-hidden','true');backdrop.innerHTML=`<section class="season-sheet" role="dialog" aria-modal="true" aria-labelledby="resultTitle"><div class="sheet-handle"></div><div class="season-sheet-head"><div><small>Season result</small><h2 id="resultTitle">Event</h2></div><button id="closeResult" type="button" aria-label="Close">×</button></div><div id="resultDetail" class="result-detail"></div><form id="correctionForm" class="correction-form"><div class="correction-head"><div><strong>Correct season facts</strong><small>Changes only your record, not shared event data.</small></div><span id="correctionStatus"></span></div><label><span>Event type</span><select id="correctionEventType"><option value="">Use recorded value</option><option value="league-challenge">League Challenge</option><option value="league-cup">League Cup</option><option value="regional">Regional</option><option value="special">Special Championship</option><option value="international">International Championship</option></select></label><div class="correction-grid"><label><span>Placement</span><input id="correctionPlacement" type="number" min="1" inputmode="numeric" placeholder="Use recorded"></label><label><span>Player count</span><input id="correctionPlayerCount" type="number" min="1" inputmode="numeric" placeholder="Use recorded"></label></div><label><span>Note <small>optional</small></span><input id="correctionNote" type="text" placeholder="Why this was corrected"></label><div class="correction-actions"><button id="clearCorrections" class="secondary-action" type="button">Clear corrections</button><button class="primary-action" type="submit">Save correction</button></div></form></section>`;document.body.appendChild(backdrop)}
if(!$('seasonToast')){const toast=document.createElement('div');toast.id='seasonToast';toast.className='season-toast hidden';toast.setAttribute('role','status');toast.setAttribute('aria-live','polite');document.body.appendChild(toast)}
const style=document.createElement('style');style.textContent=`.show-season #eventControls,.show-season .results-head,.show-season #eventList,.show-season #loadingState,.show-season #emptyState,.show-season #errorState,.show-season #savedVenuesFilter,.show-season #myTournamentsPanel{display:none!important}.season-inline-panel{margin-top:14px}.season-inline-panel.hidden{display:none!important}.season-inline-panel .season-shell{padding:0 0 28px;max-width:none}.season-inline-panel .season-head-compact{display:block;padding:2px 0 8px;margin:0}.season-inline-panel .season-head-compact h2{margin:0;font-size:18px;line-height:1.2}`;document.head.appendChild(style)}
async function ensureAssets(){if(assetsLoaded)return;if(assetsLoading)return assetsLoading;ensureStyle();assetsLoading=(async()=>{if(!window.PTCGSeasonEngine)await loadScript('../_shared/season-engine.js?v=2');if(!window.PTCGSeasonRules?.pokemon2027)await loadScript('../_shared/season-rules-2027.js?v=1');if(!window.PTCGCompetitiveSeasons?.pokemon2027)await loadScript('../_shared/season-config-2027.js?v=1');if(!window.PTCGSeasonParticipation)await loadScript('../_shared/season-participation.js?v=1');await loadScript('./season.js?v=2');assetsLoaded=true})().catch(error=>{console.error('Season view failed to load',error);const empty=$('seasonEmpty');if(empty){empty.textContent='Season view could not be loaded.';empty.classList.remove('hidden')}});return assetsLoading}
function selectSeasonTab(){document.querySelectorAll('.event-view-tabs button').forEach(control=>{control.classList.remove('active');control.setAttribute('aria-selected','false')});$('seasonTab')?.classList.add('active');$('seasonTab')?.setAttribute('aria-selected','true')}
async function show(){document.body.classList.remove('show-my-tournaments');$('myTournamentsPanel')?.classList.add('hidden');document.body.classList.add('show-season');$('seasonInlinePanel')?.classList.remove('hidden');selectSeasonTab();await ensureAssets();window.dispatchEvent(new Event('pageshow'))}
function hide(){document.body.classList.remove('show-season');$('seasonInlinePanel')?.classList.add('hidden');$('seasonTab')?.classList.remove('active');$('seasonTab')?.setAttribute('aria-selected','false')}
function bind(){inject();$('seasonTab')?.addEventListener('click',show);document.querySelectorAll('.event-view-tabs [data-view]').forEach(button=>button.addEventListener('click',hide));$('myTournamentsTab')?.addEventListener('click',hide);if(new URLSearchParams(location.search).get('view')==='season')show()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();