(function(){
'use strict';
const $=id=>document.getElementById(id);
const engine=window.PTCGSeasonEngine;
const rules=window.PTCGSeasonRules?.pokemon2027;
const season=window.PTCGCompetitiveSeasons?.pokemon2027;
const corrections=window.PTCGSeasonParticipation;
let activeResult=null;

function esc(value){return String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]))}
function eventTypeLabel(type){return ({'league-challenge':'League Challenge','league-cup':'League Cup','regional':'Regional','special':'Special Championship','international':'International Championship'})[type]||type||'Event'}
function typeClass(type){if(type==='league-challenge')return 'challenge';if(type==='league-cup')return 'cup';if(['regional','special','international'].includes(type))return 'major';return ''}
function dateLabel(value){if(!value)return 'Date unknown';const date=new Date(`${String(value).slice(0,10)}T12:00:00`);return Number.isNaN(date.getTime())?String(value):date.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}
function recordLabel(record){return `${record?.wins||0}-${record?.losses||0}-${record?.draws||0}`}
function deckLabel(ref){if(!ref)return 'No exact deck saved';return ref.deckName||ref.name||ref.displayName||ref.versionName||ref.deckId||'Saved deck version'}
function toast(message){const el=$('seasonToast');if(!el)return;el.textContent=message;el.classList.remove('hidden');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.add('hidden'),1800)}
function supportedParticipation(row){if(!row?.completion)return false;const facts=engine.effectiveParticipationFacts(row);if(facts.seasonId&&facts.seasonId!==season.id)return false;if(!facts.seasonId&&!engine.inSeason(facts.eventDate,season))return false;return !!rules.eventRules.find(rule=>engine.canonicalEventType(rule.eventType)===facts.eventType)}
function sourceRows(){return (window.PTCGStorage?.allParticipations?.()||[]).filter(supportedParticipation)}
function summary(){return engine.buildSeasonSummary(sourceRows(),season,rules)}
function byBucket(rows,bucket){const candidates=rows.filter(row=>row.bflBucketId===bucket.id);return {counting:candidates.filter(row=>row.isCounting).length,total:candidates.length,raw:candidates.reduce((sum,row)=>sum+(row.cp||0),0),countingCP:candidates.reduce((sum,row)=>sum+(row.countingCP||0),0)}}
function bflLabel(bucket){if(bucket.id==='league-challenge-bfl')return 'Challenges';if(bucket.id==='league-cup-bfl')return 'Cups';return 'Majors'}

function renderBfl(rows){const host=$('bflSummary');const section=$('bflSection');if(!host||!section)return;const cards=rules.bestFinishLimits.map(bucket=>{const stats=byBucket(rows,bucket);return `<div class="bfl-card app-card"><div><small>${esc(bflLabel(bucket))}</small><span>${stats.total?`${stats.counting} of ${stats.total} finishes counting`:`Best ${bucket.limit} finishes count`}</span></div><strong>${stats.countingCP} CP</strong></div>`});host.innerHTML=cards.join('');section.classList.remove('hidden')}
function resultCard(row){const corrected=Object.values(row.provenance||{}).includes('user-correction');const counting=row.cp>0&&row.isCounting;const footerStatus=row.cp<=0?'No CP at this finish':counting?'Counts toward season':`Excluded by ${row.bflBucketId==='major-events-bfl'?'major':'event'} BFL`;return `<button class="season-result" type="button" data-result-id="${esc(row.participationId)}"><div class="season-result-main"><div><div class="season-result-top"><span class="season-result-type ${typeClass(row.eventType)}">${esc(eventTypeLabel(row.eventType))}</span>${corrected?'<span class="season-result-corrected">Corrected</span>':''}</div><h3>${esc(row.eventName||'Completed tournament')}</h3><div class="season-result-meta"><span>${esc(dateLabel(row.eventDate))}</span><span>${esc(recordLabel(row.record))}</span>${row.placement?`<span>${esc(String(row.placement))}${row.placement===1?'st':row.placement===2?'nd':row.placement===3?'rd':'th'} / ${esc(row.playerCount||'?')}</span>`:''}</div></div><div class="season-result-cp ${row.cp>0&&!row.isCounting?'excluded':''}"><strong>${row.cp||0}</strong><small>CP</small></div></div><div class="season-result-footer"><span>${esc(deckLabel(row.usedDeckRef))}</span><span class="${counting?'counts':row.cp>0?'excluded':''}">${esc(footerStatus)}</span></div></button>`}
function renderResults(rows){const host=$('seasonResults'),empty=$('seasonEmpty');if(!host||!empty)return;const sorted=rows.slice().sort((a,b)=>String(b.completedAt||b.eventDate||'').localeCompare(String(a.completedAt||a.eventDate||'')));host.innerHTML=sorted.map(resultCard).join('');empty.classList.toggle('hidden',sorted.length>0);host.querySelectorAll('[data-result-id]').forEach(button=>button.addEventListener('click',()=>openResult(button.dataset.resultId)))}
function render(){if(!engine||!rules||!season){$('seasonEmpty').textContent='Season configuration could not be loaded.';$('seasonEmpty').classList.remove('hidden');return}const data=summary();$('seasonTitle').textContent=season.label;$('countingCP').textContent=data.countingCP;$('rawCP').textContent=data.rawCP;$('eligibleEvents').textContent=data.eligibleEvents;$('completedEvents').textContent=data.completedEvents;$('rulesPill').textContent=`2027 rules · v${rules.version}`;$('resultsHint').textContent=data.completedEvents?`${data.completedEvents} completed Championship Series event${data.completedEvents===1?'':'s'} since 1 September 2026.`:'Completed Championship Series events will appear here automatically.';renderBfl(data.results);renderResults(data.results)}

function rawParticipation(id){return window.PTCGStorage?.getParticipation?.(id)||null}
function correctionFields(row){return row?.seasonCorrection?.fields||{}}
function openResult(id){const data=summary();activeResult=data.results.find(row=>row.participationId===id)||null;if(!activeResult)return;const raw=rawParticipation(id);const fields=correctionFields(raw);$('resultTitle').textContent=activeResult.eventName||'Completed tournament';$('resultDetail').innerHTML=`<div><small>Record</small><strong>${esc(recordLabel(activeResult.record))}</strong></div><div><small>Placement</small><strong>${activeResult.placement?`${esc(activeResult.placement)} / ${esc(activeResult.playerCount||'?')}`:'Not recorded'}</strong></div><div><small>Championship Points</small><strong>${activeResult.cp||0} CP${activeResult.cp>0?(activeResult.isCounting?' · counting':' · BFL excluded'):''}</strong></div><div><small>Deck used</small><strong>${esc(deckLabel(activeResult.usedDeckRef))}</strong></div>`;$('correctionEventType').value=fields.eventType||'';$('correctionPlacement').value=fields.placement||'';$('correctionPlayerCount').value=fields.playerCount||'';$('correctionNote').value=raw?.seasonCorrection?.note||'';$('correctionStatus').textContent=raw?.seasonCorrection?'User corrected':'';$('clearCorrections').disabled=!raw?.seasonCorrection;$('resultBackdrop').classList.remove('hidden');$('resultBackdrop').setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeResult(){$('resultBackdrop').classList.add('hidden');$('resultBackdrop').setAttribute('aria-hidden','true');document.body.style.overflow='';activeResult=null}
function saveCorrection(event){event.preventDefault();if(!activeResult)return;const fields={};const type=$('correctionEventType').value;if(type)fields.eventType=type;const placement=Number($('correctionPlacement').value);if(Number.isFinite(placement)&&placement>0)fields.placement=Math.trunc(placement);const playerCount=Number($('correctionPlayerCount').value);if(Number.isFinite(playerCount)&&playerCount>0)fields.playerCount=Math.trunc(playerCount);corrections.clearAllCorrections(activeResult.participationId);if(Object.keys(fields).length||$('correctionNote').value.trim())corrections.setCorrections(activeResult.participationId,fields,{source:'user',note:$('correctionNote').value.trim()||null});const id=activeResult.participationId;render();openResult(id);toast('Season correction saved')}
function clearCorrections(){if(!activeResult)return;const id=activeResult.participationId;corrections.clearAllCorrections(id);render();openResult(id);toast('Corrections cleared')}
function bind(){if($('closeResult'))$('closeResult').addEventListener('click',closeResult);if($('resultBackdrop'))$('resultBackdrop').addEventListener('click',event=>{if(event.target===$('resultBackdrop'))closeResult()});if($('correctionForm'))$('correctionForm').addEventListener('submit',saveCorrection);if($('clearCorrections'))$('clearCorrections').addEventListener('click',clearCorrections);window.addEventListener('ptcg:local-change',()=>{if(!$('resultBackdrop').classList.contains('hidden'))return;render()});window.addEventListener('pageshow',render)}
bind();render();
})();
