(function(){
'use strict';
let incompleteActive=false;
const today=()=>new Date().toISOString().slice(0,10);
const rows=()=>window.PTCGStorage?.allParticipations?.()||[];
function rowFor(card){return window.PTCGStorage?.getParticipation?.(card?.dataset?.id)||null}
function name(row){return row?.eventSnapshot?.name||row?.eventSnapshot?.venue||row?.eventSnapshot?.city||'Tournament'}
function date(row){return String(row?.eventSnapshot?.startDate||'').slice(0,10)}
function type(row){return row?.eventSnapshot?.type||'Tournament'}
function esc(v){return String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]))}
function reopen(row){if(!row)return;window.PTCGStorage.updateParticipation(row.id,current=>{const prior=current.completion?{...current.completion}:null;current.completion=null;current.archivedAt=null;current.attendanceStatus='attending';current.tournamentDay={...(current.tournamentDay||{}),finishedAt:null,reopenedAt:new Date().toISOString(),reopenDraft:prior};return current})}
function incompleteRows(){return rows().filter(row=>row&&!row.completion&&!row.archivedAt&&date(row)&&date(row)<today()&&(row.tournamentDay||row.attendanceStatus==='attending'||row.attendanceStatus==='attended')).sort((a,b)=>date(b).localeCompare(date(a)))}
function ensureFilter(){const filters=document.getElementById('mtFilters');if(!filters||filters.querySelector('[data-incomplete-filter]'))return;const button=document.createElement('button');button.type='button';button.dataset.incompleteFilter='';button.textContent='Incomplete';button.addEventListener('click',()=>{incompleteActive=true;filters.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===button));renderIncomplete()});filters.appendChild(button);filters.addEventListener('click',event=>{if(event.target!==button&&event.target.closest('button'))incompleteActive=false})}
function renderIncomplete(){if(!incompleteActive)return;const list=document.getElementById('mtList'),summary=document.getElementById('mtSummary'),empty=document.getElementById('mtEmpty');if(!list||!summary||!empty)return;const items=incompleteRows();summary.textContent=`${items.length} incomplete tournament${items.length===1?'':'s'}`;list.innerHTML=items.map(row=>`<article class="tournament-card" data-id="${esc(row.id)}"><div class="tournament-card-main"><div><h2>${esc(name(row))}</h2><div class="tournament-meta"><span>${esc(date(row))}</span><span>${esc(type(row))}</span></div></div><span class="tournament-status needs">Incomplete</span></div><div class="tournament-actions"><a class="open" href="./tournament-day.html?participation=${encodeURIComponent(row.id)}">Open</a></div></article>`).join('');empty.classList.toggle('hidden',items.length>0)}
function routeAfterReopen(row){const d=date(row);if(d>today())document.querySelector('#mtFilters [data-filter="upcoming"]')?.click();else if(d===today())document.querySelector('#mtFilters [data-filter="current"]')?.click();else document.querySelector('#mtFilters [data-incomplete-filter]')?.click()}
function enhance(){ensureFilter();document.querySelectorAll('#mtList .tournament-card').forEach(card=>{if(card.querySelector('[data-reopen]'))return;const row=rowFor(card);if(!row||( !row.completion && !row.archivedAt))return;const menu=card.querySelector('.tournament-menu');if(!menu)return;const button=document.createElement('button');button.type='button';button.dataset.reopen='';button.textContent='Reopen tournament';button.addEventListener('click',()=>{reopen(row);setTimeout(()=>routeAfterReopen(window.PTCGStorage.getParticipation(row.id)),0)});menu.prepend(button)});if(incompleteActive)renderIncomplete()}
function bind(){const host=document.getElementById('myTournamentsPanel');if(host)new MutationObserver(()=>setTimeout(enhance,0)).observe(host,{childList:true,subtree:true});window.addEventListener('ptcg:local-change',()=>setTimeout(enhance,30));setTimeout(enhance,100)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();