(function(){
'use strict';
const $=id=>document.getElementById(id);
let filter='all';
let spriteIndexPromise=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]));
function state(){return window.PTCGStorage?.load?.()||{eventParticipations:[]}}
function rows(){return (state().eventParticipations||[]).filter(row=>row&&(row.source==='manual'||row.tournamentDay||row.completion||['attending','attended'].includes(row.attendanceStatus)))}
function matchRows(id){return (window.PTCGMatchStore?.all?.()||[]).filter(match=>match.participationId===id)}
function stats(id){return window.PTCGMatchStore?.stats?.(matchRows(id))||{wins:0,losses:0,draws:0,total:0}}
function dateOf(row){const d=row?.eventSnapshot?.startDate;return d?new Date(`${d}T12:00:00`):null}
function isPastDate(row){const d=dateOf(row);return d?d.getTime()<Date.now():false}
function status(row){if(row.archivedAt)return'archived';if(row.completion)return'completed';if(row.tournamentDay)return'in-progress';if(row.phase==='needs-completion'||(row.attendanceStatus==='attended'&&!row.completion)||isPastDate(row))return'needs-completion';return'upcoming'}
function filtered(){return rows().filter(row=>{const s=status(row);if(filter==='all')return s!=='archived';if(filter==='current')return s==='in-progress'||s==='needs-completion';return s===filter}).sort((a,b)=>{const ad=dateOf(a)?.getTime()||0,bd=dateOf(b)?.getTime()||0;return filter==='completed'||filter==='archived'||filter==='all'?bd-ad:ad-bd})}
function name(row){const s=row.eventSnapshot||{};return s.name||s.venue||s.city||'Tournament'}
function type(row){return row.eventSnapshot?.type||'Tournament'}
function fmtDate(row){const d=dateOf(row);return d&&!Number.isNaN(d.getTime())?d.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}):'No date'}
function deckLabel(row){const ref=row.usedDeckRef||row.plannedDeckRef||{};return ref.deckNameSnapshot||ref.archetypeSnapshot||'Deck not selected'}
function deckArchetype(row){const ref=row.usedDeckRef||row.plannedDeckRef||{};return ref.archetypeSnapshot||ref.deckNameSnapshot||''}
function statusLabel(row){const s=status(row);return s==='in-progress'?'In progress':s==='needs-completion'?'Needs completion':s==='completed'?'Completed':s==='archived'?'Archived':'Upcoming'}
function statusClass(row){const s=status(row);return s==='in-progress'?'live':s==='completed'?'done':s==='needs-completion'?'needs':''}
function placement(row){const p=row.completion?.placement,c=row.completion?.playerCount;return p?`${ordinal(p)}${c?` / ${c}`:''}`:null}
function ordinal(n){const v=Number(n);if(!Number.isFinite(v))return String(n);const m=v%100;if(m>=11&&m<=13)return`${v}th`;return`${v}${v%10===1?'st':v%10===2?'nd':v%10===3?'rd':'th'}`}
function index(){if(!spriteIndexPromise)spriteIndexPromise=window.PTCGSprites?.getIndex?.().catch(()=>[])||Promise.resolve([]);return spriteIndexPromise}
function normalise(t){return String(t||'').toLowerCase().replace(/[^a-z0-9\s-]/g,' ').replace(/\b(ex|vstar|vmax|v|gx|mega)\b/g,' ').replace(/\s+/g,' ').trim()}
function namesFrom(text,items){const source=` ${normalise(text)} `,found=[];for(const item of items){const phrase=String(item.name||'').toLowerCase().replace(/-/g,' ');if(phrase.length>=3&&source.includes(` ${phrase} `))found.push({name:item.name,len:phrase.length})}return found.sort((a,b)=>b.len-a.len).filter((x,i,a)=>a.findIndex(y=>y.name===x.name)===i).slice(0,2).map(x=>x.name)}
async function fillSprites(text,el){if(!el||!window.PTCGSprites)return;const items=await index(),names=namesFrom(text,items);const sprites=await Promise.all(names.map(n=>window.PTCGSprites.fetchSprite(n).catch(()=>null)));el.innerHTML=sprites.filter(Boolean).map(s=>s.spriteUrl?`<img src="${esc(s.spriteUrl)}" alt="">`:'').join('')}
function card(row){const st=stats(row.id),place=placement(row),linked=row.eventId?'Linked event':'Standalone';return `<article class="tournament-card" data-id="${esc(row.id)}"><div class="tournament-card-main"><div><h2>${esc(name(row))}</h2><div class="tournament-meta"><span>${esc(fmtDate(row))}</span><span>${esc(type(row))}</span><span>${linked}</span></div></div><span class="tournament-status ${statusClass(row)}">${statusLabel(row)}</span></div><div class="tournament-body"><div class="tournament-deck"><span class="tournament-deck-sprites" data-deck-sprites></span><span class="tournament-deck-copy"><small>Deck</small><strong>${esc(deckLabel(row))}</strong></span></div><div class="tournament-record"><strong>${st.wins}-${st.losses}-${st.draws}</strong><small>${place?`${esc(place)} · `:''}${st.total} rounds</small></div></div><div class="opponent-preview" data-opponents></div><div class="tournament-actions"><a class="open" href="./tournament-day.html?build=20260903-2128&participation=${encodeURIComponent(row.id)}">${status(row)==='upcoming'?'Open':'View tournament'}</a><button type="button" data-edit>Edit</button><button type="button" class="menu-button" data-menu>•••</button></div><div class="tournament-menu"><button type="button" data-archive>${row.archivedAt?'Restore':'Archive'}</button><button type="button" class="danger" data-delete>Delete tournament</button></div></article>`}
async function decorate(article,row){fillSprites(deckArchetype(row),article.querySelector('[data-deck-sprites]'));const opponents=matchRows(row.id).slice(-4).map(m=>m.opponentArchetype).filter(Boolean),host=article.querySelector('[data-opponents]');for(const opponent of opponents){const span=document.createElement('span');host.appendChild(span);await fillSprites(opponent,span)}}
function render(){const all=rows(),current=all.filter(r=>['in-progress','needs-completion'].includes(status(r))).length,upcoming=all.filter(r=>status(r)==='upcoming').length,completed=all.filter(r=>status(r)==='completed').length;$('tournamentSummary').innerHTML=`<span>${current} current</span><span>${upcoming} upcoming</span><span>${completed} completed</span>`;const list=filtered();$('tournamentList').innerHTML=list.map(card).join('');$('emptyState').classList.toggle('hidden',!!list.length);$('tournamentList').querySelectorAll('.tournament-card').forEach(article=>{const row=rows().find(r=>r.id===article.dataset.id);if(row)decorate(article,row);article.querySelector('[data-menu]').addEventListener('click',()=>article.classList.toggle('menu-open'));article.querySelector('[data-edit]').addEventListener('click',()=>openEdit(row));article.querySelector('[data-archive]').addEventListener('click',()=>toggleArchive(row));article.querySelector('[data-delete]').addEventListener('click',()=>deleteTournament(row))})}
function openEdit(row){if(!row)return;$('editId').value=row.id;$('editName').value=name(row);$('editDate').value=row.eventSnapshot?.startDate||'';$('editType').value=type(row);$('editBackdrop').classList.remove('hidden');$('editBackdrop').setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeEdit(){$('editBackdrop').classList.add('hidden');$('editBackdrop').setAttribute('aria-hidden','true');document.body.style.overflow=''}
function saveEdit(e){e.preventDefault();const id=$('editId').value,n=$('editName').value.trim();if(!n)return toast('Give the tournament a name');window.PTCGStorage.updateParticipation(id,row=>{row.eventSnapshot={...(row.eventSnapshot||{}),name:n,startDate:$('editDate').value||row.eventSnapshot?.startDate||null,type:$('editType').value||row.eventSnapshot?.type||'Tournament'};return row});closeEdit();render();toast('Tournament updated')}
function toggleArchive(row){const restoring=!!row.archivedAt;window.PTCGStorage.updateParticipation(row.id,current=>{current.archivedAt=current.archivedAt?null:new Date().toISOString();return current});render();toast(restoring?'Tournament restored':'Tournament archived')}
function deleteTournament(row){if(!confirm(`Delete ${name(row)} and all of its recorded rounds? This cannot be undone.`))return;for(const match of matchRows(row.id))window.PTCGMatchStore.remove(match.id);window.PTCGStorage.update(s=>{s.eventParticipations=(s.eventParticipations||[]).filter(item=>item.id!==row.id);return s});render();toast('Tournament deleted')}
function toast(msg){const el=$('toast');el.textContent=msg;el.classList.remove('hidden');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.add('hidden'),1800)}
function bind(){document.querySelectorAll('[data-filter]').forEach(btn=>btn.addEventListener('click',()=>{filter=btn.dataset.filter;document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b===btn));render()}));$('closeEdit').addEventListener('click',closeEdit);$('editBackdrop').addEventListener('click',e=>{if(e.target===$('editBackdrop'))closeEdit()});$('editForm').addEventListener('submit',saveEdit);window.addEventListener('ptcg:local-change',()=>setTimeout(render,0));render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();