(function(){
'use strict';
const $=id=>document.getElementById(id);
const participationId=new URLSearchParams(location.search).get('participation');
let participation=null,decks=[],matches=[],editingId=null;
const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]));
const now=()=>new Date().toISOString();
function toast(message){const el=$('toast');el.textContent=message;el.classList.remove('hidden');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.add('hidden'),2100)}
function setSaved(text='Saved'){$('saveState').textContent=text}
function eventName(){const s=participation?.eventSnapshot||{};return s.name||s.venue||s.city||'Tournament'}
function eventDate(){const s=participation?.eventSnapshot||{};if(!s.startDate)return null;const d=new Date(`${s.startDate}T12:00:00`);return Number.isNaN(d.getTime())?null:d}
function loadParticipation(){participation=window.PTCGStorage?.getParticipation?.(participationId);if(!participation)throw new Error('This event participation could not be found.')}
function eventMatches(){return window.PTCGMatchStore.all().filter(match=>match.participationId===participation.id).sort((a,b)=>roundNumber(a)-roundNumber(b)||Date.parse(a.playedAt)-Date.parse(b.playedAt))}
function roundNumber(match){const found=String(match?.roundLabel||'').match(/\d+/);return found?Number(found[0]):999}
function record(){return window.PTCGMatchStore.stats(matches)}
function renderEvent(){const s=participation.eventSnapshot||{};$('eventTitle').textContent=eventName();$('headerEvent').textContent=eventName();const bits=[];const d=eventDate();if(d)bits.push(d.toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short',year:'numeric'}));if(s.venue)bits.push(s.venue);else if(s.city)bits.push(s.city);$('eventMeta').textContent=bits.join(' · ')||'Saved event'}
function versionForRef(ref){if(!ref?.deckId)return null;const deck=decks.find(d=>d.id===ref.deckId);if(!deck)return null;const version=window.PTCGDeckStore.getVersion(deck,ref.deckVersionId);return version?{deck,version}:null}
function refSnapshot(deck,version){return {deckId:deck.id,deckVersionId:version.id,listHash:version.listHash,deckNameSnapshot:deck.name||null,deckVersionLabelSnapshot:version.name?`${version.label} · ${version.name}`:version.label||null,archetypeSnapshot:deck.archetype||null,selectedAt:now()}}
function deckRefLabel(ref){if(!ref)return 'No exact list recorded';const live=versionForRef(ref);const name=live?.deck?.name||ref.deckNameSnapshot||'Saved deck';const version=live?.version?(live.version.name?`${live.version.label} · ${live.version.name}`:live.version.label):(ref.deckVersionLabelSnapshot||'Exact list');return `${name} · ${version}`}
function updateParticipation(mutator){participation=window.PTCGStorage.updateParticipation(participation.id,row=>{mutator(row);return row});setSaved();return participation}
function isStarted(){return !!participation.tournamentDay}
function isCompleted(){return !!participation.completion}
function selectedDeck(){return decks.find(d=>d.id===$('deckSelect').value)||null}
function renderDeckSelectors(){const planned=participation.plannedDeckRef;const sorted=[...decks].sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0));const prior=$('deckSelect').value||planned?.deckId||'';$('deckSelect').innerHTML=`<option value="">Choose a deck</option>${sorted.map(deck=>`<option value="${esc(deck.id)}">${esc(deck.name)}${deck.archetype?` · ${esc(deck.archetype)}`:''}</option>`).join('')}`;if(sorted.some(d=>d.id===prior))$('deckSelect').value=prior;renderVersions();$('plannedHint').textContent=planned?`Planned: ${deckRefLabel(planned)}`:'No exact list was selected in Event Prep.'}
function renderVersions(){const deck=selectedDeck(),planned=participation?.plannedDeckRef;const versions=deck?.versions||[];const prior=$('versionSelect').value||(planned?.deckId===deck?.id?planned.deckVersionId:'')||deck?.currentVersionId||'';$('versionSelect').innerHTML=`<option value="">Choose an exact version</option>${versions.slice().reverse().map(v=>`<option value="${esc(v.id)}">${esc(v.name?`${v.label} · ${v.name}`:v.label)}</option>`).join('')}`;if(versions.some(v=>v.id===prior))$('versionSelect').value=prior}
function startTournament(){if(isStarted())return;const deck=selectedDeck(),version=deck&&window.PTCGDeckStore.getVersion(deck,$('versionSelect').value);let used=null;if(deck&&version&&version.listHash)used=refSnapshot(deck,version);else if(participation.plannedDeckRef?.listHash){used={...participation.plannedDeckRef,deckNameSnapshot:participation.plannedDeckRef.deckNameSnapshot||null,deckVersionLabelSnapshot:participation.plannedDeckRef.deckVersionLabelSnapshot||null,selectedAt:now()}}if(!used){toast('Choose an exact saved DeckVersion');return}updateParticipation(row=>{if(row.plannedDeckRef&&!row.plannedDeckRef.deckNameSnapshot){const live=versionForRef(row.plannedDeckRef);if(live)row.plannedDeckRef={...row.plannedDeckRef,deckNameSnapshot:live.deck.name||null,deckVersionLabelSnapshot:live.version.name?`${live.version.label} · ${live.version.name}`:live.version.label||null,archetypeSnapshot:live.deck.archetype||null}}row.usedDeckRef=used;row.tournamentDay={startedAt:now(),lastOpenedAt:now()};if(row.attendanceStatus!=='attended')row.attendanceStatus='attending'});render();toast('Tournament started')}
function scoreText(match){const s=window.PTCGMatchStore.score(match);const parts=[s.wins,s.losses];if(s.draws)parts.push(s.draws);return parts.join('-')}
function resultLabel(result){return result==='win'?'W':result==='loss'?'L':result==='draw'?'D':'?'}
function renderHistory(){if(!matches.length){$('roundHistory').innerHTML='<div class="td-empty">No rounds recorded yet.</div>';return}$('roundHistory').innerHTML=matches.map(match=>`<button class="round-row" type="button" data-match-id="${esc(match.id)}"><span class="result-badge ${esc(match.result)}">${resultLabel(match.result)}</span><span class="round-copy"><strong>${esc(match.roundLabel||'Round')}</strong><small>${esc(match.opponentArchetype||'Opponent not recorded')} · ${esc(scoreText(match))}</small></span><span class="round-edit">Edit</span></button>`).join('');$('roundHistory').querySelectorAll('[data-match-id]').forEach(button=>button.addEventListener('click',()=>openRound(button.dataset.matchId)))}
function render(){matches=eventMatches();const stats=record();$('recordValue').textContent=`${stats.wins}-${stats.losses}-${stats.draws}`;$('roundsValue').textContent=String(stats.total);$('deckSummary').innerHTML=`<small>Playing</small><strong>${esc(deckRefLabel(participation.usedDeckRef||participation.plannedDeckRef))}</strong>`;const next=stats.total+1;$('addRound').textContent=`Add Round ${next}`;$('addRound').disabled=!isStarted()||isCompleted();$('completeEvent').disabled=isCompleted();$('completeEvent').textContent=isCompleted()?'Event completed':'Complete event';$('startCard').classList.toggle('hidden',isStarted()||isCompleted());renderDeckSelectors();renderHistory();const qp=new URLSearchParams({participation:participation.id,w:String(stats.wins),l:String(stats.losses),d:String(stats.draws)});$('cutIdLink').href=`../tools/?${qp.toString()}#cut`;setSaved(isCompleted()?'Completed':'Saved')}
function openSheet(id){const el=$(id);el.classList.remove('hidden');el.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeSheet(id){const el=$(id);el.classList.add('hidden');el.setAttribute('aria-hidden','true');document.body.style.overflow=''}
function setRadio(name,value){document.querySelectorAll(`input[name="${name}"]`).forEach(input=>input.checked=input.value===value)}
function openRound(id=null){if(!isStarted()||isCompleted())return;editingId=id;const match=id?window.PTCGMatchStore.get(id):null;const next=matches.length+1;$('matchId').value=match?.id||'';$('roundSheetEyebrow').textContent=match?'Correct round':'Next round';$('roundSheetTitle').textContent=match?`Edit ${match.roundLabel||'round'}`:`Add Round ${next}`;$('roundLabel').value=match?.roundLabel||`Round ${next}`;$('opponentArchetype').value=match?.opponentArchetype||'';setRadio('result',match?.result||'');const score=match?window.PTCGMatchStore.score(match):{wins:0,losses:0,draws:0};$('gameWins').value=score.wins;$('gameLosses').value=score.losses;$('gameDraws').value=score.draws;setRadio('wentFirst',match?.wentFirst===true?'first':match?.wentFirst===false?'second':'');$('roundNotes').value=match?.notes||'';$('deleteRound').classList.toggle('hidden',!match);openSheet('roundBackdrop')}
function saveRound(event){event.preventDefault();const result=document.querySelector('input[name="result"]:checked')?.value;if(!['win','loss','draw'].includes(result)){toast('Choose Win, Loss or Draw');return}const turn=document.querySelector('input[name="wentFirst"]:checked')?.value;const used=participation.usedDeckRef||{};const existing=editingId?window.PTCGMatchStore.get(editingId):null;const playedAt=existing?.playedAt||now();const wins=Number($('gameWins').value)||0,losses=Number($('gameLosses').value)||0,draws=Number($('gameDraws').value)||0;if(wins+losses+draws<1){toast('Enter the game score');return}const scoreResult=wins>losses?'win':losses>wins?'loss':'draw';if(scoreResult!==result){toast('Match result and game score do not agree');return}const games=window.PTCGMatchStore.gamesFromScore(wins,losses,draws,turn==='first'?true:turn==='second'?false:null);window.PTCGMatchStore.put({...(existing||{}),id:existing?.id||undefined,source:'irl',playedAt,result,deckId:used.deckId||null,deckVersionId:used.deckVersionId||null,listHash:used.listHash||null,deckNameSnapshot:used.deckNameSnapshot||null,deckVersionLabelSnapshot:used.deckVersionLabelSnapshot||null,opponentArchetype:$('opponentArchetype').value.trim()||null,wentFirst:turn==='first'?true:turn==='second'?false:null,participationId:participation.id,eventId:participation.eventId,eventName:eventName(),roundLabel:$('roundLabel').value.trim()||`Round ${matches.length+1}`,notes:$('roundNotes').value.trim(),games});updateParticipation(row=>{row.tournamentDay={...(row.tournamentDay||{}),lastOpenedAt:now(),lastRoundAt:now()}});closeSheet('roundBackdrop');render();toast(existing?'Round corrected':'Round saved')}
function deleteRound(){if(!editingId)return;window.PTCGMatchStore.remove(editingId);updateParticipation(row=>{row.tournamentDay={...(row.tournamentDay||{}),lastOpenedAt:now()}});closeSheet('roundBackdrop');editingId=null;render();toast('Round deleted')}
function openCompletion(){if(isCompleted())return;if(!participation.usedDeckRef){toast('Confirm the exact list you used first');$('startCard').scrollIntoView({behavior:'smooth',block:'start'});return}const stats=record();$('completionRecord').innerHTML=`<strong>${stats.wins}-${stats.losses}-${stats.draws}</strong><span>${stats.total} rounds · ${esc(deckRefLabel(participation.usedDeckRef))}</span>`;$('placement').value=participation.completion?.placement||'';$('playerCount').value=participation.completion?.playerCount||'';$('completionNotes').value=participation.completion?.notes||'';openSheet('completionBackdrop')}
function completeEvent(event){event.preventDefault();const placement=Number($('placement').value),playerCount=Number($('playerCount').value);if(!Number.isFinite(placement)||placement<1){toast('Enter your final placement');return}if(!Number.isFinite(playerCount)||playerCount<1){toast('Enter the final player count');return}if(placement>playerCount){toast('Placement cannot exceed player count');return}const stats=record();updateParticipation(row=>{row.attendanceStatus='attended';row.completion={completedAt:now(),placement,playerCount,record:{wins:stats.wins,losses:stats.losses,draws:stats.draws},roundsCompleted:stats.total,usedDeckRef:row.usedDeckRef?{...row.usedDeckRef}:null,notes:$('completionNotes').value.trim()||null};row.tournamentDay=row.tournamentDay?{...row.tournamentDay,finishedAt:now()}:null});closeSheet('completionBackdrop');render();toast('Event completed')}
async function loadArchetypes(){try{await window.PTCGArchetypes?.load?.();window.PTCGArchetypes?.mergeSaved?.(decks.map(d=>d.archetype).filter(Boolean));const rows=window.PTCGArchetypes?.search?.('',80)||[];$('archetypeOptions').innerHTML=rows.map(row=>`<option value="${esc(row.name)}"></option>`).join('')}catch(error){console.warn('Archetype suggestions unavailable',error)}}
function bind(){$('deckSelect').addEventListener('change',renderVersions);$('versionSelect').addEventListener('change',renderVersions);$('startTournament').addEventListener('click',startTournament);$('addRound').addEventListener('click',()=>openRound());$('roundForm').addEventListener('submit',saveRound);$('deleteRound').addEventListener('click',deleteRound);$('completeEvent').addEventListener('click',openCompletion);$('completionForm').addEventListener('submit',completeEvent);$('closeRoundSheet').addEventListener('click',()=>closeSheet('roundBackdrop'));$('closeCompletion').addEventListener('click',()=>closeSheet('completionBackdrop'));['roundBackdrop','completionBackdrop'].forEach(id=>$(id).addEventListener('click',event=>{if(event.target===$(id))closeSheet(id)}))}
async function init(){try{loadParticipation();renderEvent();await window.PTCGDeckStore.open();decks=await window.PTCGDeckStore.all();if(participation.tournamentDay&&!participation.completion)updateParticipation(row=>{row.tournamentDay={...row.tournamentDay,lastOpenedAt:now()}});bind();render();$('workspace').classList.remove('hidden');loadArchetypes()}catch(error){console.error(error);$('fatal').textContent=error.message;$('fatal').classList.remove('hidden');setSaved('Unavailable')}}
init();
})();