(function(){
'use strict';
const $=id=>document.getElementById(id);let filter='all',spriteIndexPromise=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[ch]));
const state=()=>window.PTCGStorage?.load?.()||{eventParticipations:[]};
const rows=()=> (state().eventParticipations||[]).filter(r=>r&&(r.source==='manual'||r.tournamentDay||r.completion||['attending','attended'].includes(r.attendanceStatus)));
const matches=id=>(window.PTCGMatchStore?.all?.()||[]).filter(m=>m.participationId===id);
const stats=id=>window.PTCGMatchStore?.stats?.(matches(id))||{wins:0,losses:0,draws:0,total:0};
function dateOf(r){const d=r?.eventSnapshot?.startDate;return d?new Date(`${d}T12:00:00`):null}
function status(r){if(r.archivedAt)return'archived';if(r.completion)return'completed';if(r.tournamentDay)return'in-progress';const d=dateOf(r);if(r.phase==='needs-completion'||r.attendanceStatus==='attended'||(d&&d.getTime()<Date.now()))return'needs-completion';return'upcoming'}
function filtered(){return rows().filter(r=>{const s=status(r);if(filter==='all')return s!=='archived';if(filter==='current')return s==='in-progress'||s==='needs-completion';return s===filter}).sort((a,b)=>(dateOf(b)?.getTime()||0)-(dateOf(a)?.getTime()||0))}
const name=r=>r.eventSnapshot?.name||r.eventSnapshot?.venue||r.eventSnapshot?.city||'Tournament';
const type=r=>r.eventSnapshot?.type||'Tournament';
function fmtDate(r){const d=dateOf(r);return d&&!Number.isNaN(d)?d.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}):'No date'}
function playedRef(r){return r.usedDeckRef?.deckId?r.usedDeckRef:null}
function deckText(r){const ref=playedRef(r);return ref?.deckNameSnapshot||ref?.archetypeSnapshot||'Deck not selected'}
function statusLabel(r){return status(r)==='in-progress'?'In progress':status(r)==='needs-completion'?'Needs completion':status(r)==='completed'?'Completed':status(r)==='archived'?'Archived':'Upcoming'}
function statusClass(r){return status(r)==='in-progress'?'live':status(r)==='completed'?'done':status(r)==='needs-completion'?'needs':''}
function ordinal(n){const v=Number(n),m=v%100;if(m>=11&&m<=13)return`${v}th`;return`${v}${v%10===1?'st':v%10===2?'nd':v%10===3?'rd':'th'}`}
function placement(r){const p=r.completion?.placement,c=r.completion?.playerCount;return p?`${ordinal(p)}${c?` / ${c}`:''}`:''}
function card(r){const st=stats(r.id),hasResults=st.total>0,ref=playedRef(r),place=placement(r);return `<article class="tournament-card${hasResults?' has-results':''}" data-id="${esc(r.id)}"><div class="tournament-card-main"><div><h2>${esc(name(r))}</h2><div class="tournament-meta"><span>${esc(fmtDate(r))}</span><span>${esc(type(r))}</span></div></div><span class="tournament-status ${statusClass(r)}">${statusLabel(r)}</span></div><div class="tournament-body"><div class="tournament-deck"><span class="tournament-deck-sprites" data-deck-sprites></span><span class="tournament-deck-copy"><small>${hasResults?'Played':'Deck'}</small><strong>${esc(deckText(r))}</strong></span></div><div class="tournament-record"><strong>${st.wins}-${st.losses}-${st.draws}</strong><small>${place?`${esc(place)} · `:''}${st.total} rounds</small></div></div><div class="tournament-actions"><a class="open" href="./tournament-day.html?build=20260903-2155&participation=${encodeURIComponent(r.id)}">${hasResults?'View':'Open'}</a><button type="button" data-edit>Edit</button><button type="button" class="menu-button" data-menu>•••</button></div><div class="tournament-menu">${ref?'<button type="button" data-remove-deck>Remove deck</button>':''}<button type="button" data-archive>${r.archivedAt?'Restore':'Archive'}</button><button type="button" class="danger" data-delete>Delete</button></div></article>`}
function index(){if(!spriteIndexPromise)spriteIndexPromise=window.PTCGSprites?.getIndex?.().catch(()=>[])||Promise.resolve([]);return spriteIndexPromise}
function norm(t){return String(t||'').toLowerCase().replace(/[^a-z0-9\s-]/g,' ').replace(/\b(ex|vstar|vmax|v|gx|mega)\b/g,' ').replace(/\s+/g,' ').trim()}
async function sprites(text,host){if(!text||!host)return;const src=` ${norm(text)} `,items=await index(),found=[];for(const x of items){const p=String(x.name||'').toLowerCase().replace(/-/g,' ');if(p.length>=3&&src.includes(` ${p} `))found.push({name:x.name,len:p.length})}const names=found.sort((a,b)=>b.len-a.len).slice(0,2).map(x=>x.name),res=await Promise.all(names.map(n=>window.PTCGSprites.fetchSprite(n).catch(()=>null)));host.innerHTML=res.filter(Boolean).map(x=>x.spriteUrl?`<img src="${esc(x.spriteUrl)}" alt="">`:'').join('')}
function render(){const all=rows(),list=filtered();$('mtSummary').textContent=`${all.filter(r=>['in-progress','needs-completion'].includes(status(r))).length} current · ${all.filter(r=>status(r)==='upcoming').length} upcoming · ${all.filter(r=>status(r)==='completed').length} completed`;$('mtList').innerHTML=list.map(card).join('');$('mtEmpty').classList.toggle('hidden',list.length>0);$('mtList').querySelectorAll('.tournament-card').forEach(el=>{const r=rows().find(x=>x.id===el.dataset.id);const ref=playedRef(r);if(ref)sprites(ref.archetypeSnapshot||ref.deckNameSnapshot,el.querySelector('[data-deck-sprites]'));el.querySelector('[data-menu]')?.addEventListener('click',()=>el.classList.toggle('menu-open'));el.querySelector('[data-edit]')?.addEventListener('click',()=>openEdit(r));el.querySelector('[data-remove-deck]')?.addEventListener('click',()=>removeDeck(r));el.querySelector('[data-archive]')?.addEventListener('click',()=>{window.PTCGStorage.updateParticipation(r.id,x=>{x.archivedAt=x.archivedAt?null:new Date().toISOString();return x});render()});el.querySelector('[data-delete]')?.addEventListener('click',()=>deleteTournament(r))})}
function openEdit(r){$('mtEditId').value=r.id;$('mtEditName').value=name(r);$('mtEditDate').value=r.eventSnapshot?.startDate||'';$('mtEditType').value=type(r);$('mtEditBackdrop').classList.remove('hidden')}
function closeEdit(){$('mtEditBackdrop').classList.add('hidden')}
function saveEdit(e){e.preventDefault();const id=$('mtEditId').value,n=$('mtEditName').value.trim();if(!n)return;window.PTCGStorage.updateParticipation(id,r=>{r.eventSnapshot={...(r.eventSnapshot||{}),name:n,startDate:$('mtEditDate').value||null,type:$('mtEditType').value||'Tournament'};return r});closeEdit();render()}
function removeDeck(r){window.PTCGStorage.updateParticipation(r.id,x=>{x.usedDeckRef=null;return x});for(const m of matches(r.id))window.PTCGMatchStore.put({...m,deckId:null,deckVersionId:null,listHash:null,deckNameSnapshot:null,deckVersionLabelSnapshot:null});render()}
function deleteTournament(r){if(!confirm(`Delete ${name(r)} and all recorded rounds?`))return;for(const m of matches(r.id))window.PTCGMatchStore.remove(m.id);window.PTCGStorage.update(s=>{s.eventParticipations=(s.eventParticipations||[]).filter(x=>x.id!==r.id);return s});render()}
function show(){document.body.classList.add('show-my-tournaments');$('myTournamentsPanel').classList.remove('hidden');document.querySelectorAll('.event-view-tabs button').forEach(b=>b.setAttribute('aria-selected',b.id==='myTournamentsTab'?'true':'false'));render()}
function hide(){document.body.classList.remove('show-my-tournaments');$('myTournamentsPanel').classList.add('hidden')}
function bind(){$('myTournamentsTab')?.addEventListener('click',show);document.querySelectorAll('.event-view-tabs [data-view]').forEach(b=>b.addEventListener('click',hide));document.querySelectorAll('#mtFilters [data-filter]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;document.querySelectorAll('#mtFilters [data-filter]').forEach(x=>x.classList.toggle('active',x===b));render()}));$('mtCloseEdit')?.addEventListener('click',closeEdit);$('mtEditBackdrop')?.addEventListener('click',e=>{if(e.target===$('mtEditBackdrop'))closeEdit()});$('mtEditForm')?.addEventListener('submit',saveEdit);window.addEventListener('ptcg:local-change',()=>{if(document.body.classList.contains('show-my-tournaments'))render()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();