(function(){
'use strict';
const $=id=>document.getElementById(id);
const participationId=new URLSearchParams(location.search).get('participation');
let participation=null,decks=[],matches=[],editingId=null;
const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]));
const now=()=>new Date().toISOString();
function toast(message){const el=$('toast');el.textContent=message;el.classList.remove('hidden');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.add('hidden'),2100)}
function setSaved(text='Saved'){$('saveState').textContent=text}
function eventName(){const s=participation?.eventSnapshot||{};return s.name||s.venue||s.city||'Tournament'}
function eventDate(){const s=participation?.eventSnapshot||{};if(!s.startDate)return null;const d=new Date(`${s.startDate}T12:00:00`);return Number.isNaN(d.getTime())?null:d}
function loadParticipation(){participation=window.PTCGStorage?.getParticipation?.(participationId);if(!participation)throw new Error('This event participation could not be found.')}
function eventMatches(){return window.PTCGMatchStore.all().filter(match=>match.participationId===participation.id).sort((a,b)=>roundNumber(a)-roundNumber(b)||Date.parse(a.playedAt)-Date.parse(b.playedAt))}
function roundNumber(match){const found=String(match?.roundLabel||'').match(/\d+/);return found?Number(found[0]):999}
function record(){return window.PTCGMatchStore.stats(matches)}
function renderEvent(){const s=participation.eventSnapshot||{};$('eventTitle').textContent=eventName();$('headerEvent').textContent=eventName();const bits=[];const d=eventDate();if(d)bits.push(d.toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short',year:'numeric'}));if(s.venue)bits.push(s.venue);else if(s.city)bits.push(s.city);$('eventMeta').textContent=bits.join(' · ')||'Saved event'}
function deckRefLabel(ref){if(!ref)return 'No exact list recorded';const name=ref.deckNameSnapshot||ref.archetypeSnapshot||'Saved deck';const version=ref.deckVersionLabelSnapshot||'Exact list';return `${name} · ${version}`}
function updateParticipation(mutator){participation=window.PTCGStorage.updateParticipation(participation.id,row=>{mutator(row);return row});setSaved();return participation}
function isStarted(){return !!participation.tournamentDay}
function isCompleted(){return !!participation.completion}
function ensureStarted(){if(isStarted()||isCompleted())return;updateParticipation(row=>{row.tournamentDay={startedAt:now(),lastOpenedAt:now()};if(row.attendanceStatus!=='attended')row.attendanceStatus='attending'})}
function scoreText(match){const s=window.PTCGMatchStore.score(match);const parts=[s.wins,s.losses];if(s.draws)parts.push(s.draws);return parts.join('-')}
function resultLabel(result){return result==='win'?'W':result==='loss'?'L':result==='draw'?'D':'?'}
function renderHistory(){if(!matches.length){$('roundHistory').innerHTML='<div class="td-empty">No rounds recorded yet.</div>';return}$('roundHistory').innerHTML=matches.map(match=>`<button class="round-row" type="button" data-match-id="${esc(match.id)}"><span class="result-badge ${esc(match.result)}">${resultLabel(match.result)}</span><span class="round-copy"><strong>${esc(match.roundLabel||'Round')}</strong><small>${esc(match.opponentArchetype||'Opponent not recorded')} · ${esc(scoreText(match))}</small></span><span class="round-edit">Edit</span></button>`).join('');$('roundHistory').querySelectorAll('[data-match-id]').forEach(button=>button.addEventListener('click',()=>openRound(button.dataset.matchId)))}
function render(){matches=eventMatches();const stats=record();$('recordValue').textContent=`${stats.wins}-${stats.losses}-${stats.draws}`;$('roundsValue').textContent=String(stats.total);const next=stats.total+1;$('addRound').textContent=`Add Round ${next}`;$('addRound').disabled=!isStarted()||isCompleted();$('openIdCalc').disabled=!isStarted()||isCompleted()||!matches.length;$('completeEvent').disabled=isCompleted();$('completeEvent').textContent=isCompleted()?'Event completed':'Complete event';renderHistory();setSaved(isCompleted()?'Completed':'Saved')}
function openSheet(id){const el=$(id);el.classList.remove('hidden');el.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeSheet(id){const el=$(id);el.classList.add('hidden');el.setAttribute('aria-hidden','true');document.body.style.overflow=''}
function setRadio(name,value){document.querySelectorAll(`input[name="${name}"]`).forEach(input=>input.checked=input.value===value)}
function openRound(id=null){if(!isStarted()||isCompleted())return;editingId=id;const match=id?window.PTCGMatchStore.get(id):null;const next=matches.length+1;$('matchId').value=match?.id||'';$('roundSheetEyebrow').textContent=match?'Correct round':'Next round';$('roundSheetTitle').textContent=match?`Edit ${match.roundLabel||'round'}`:`Add Round ${next}`;$('roundLabel').value=match?.roundLabel||`Round ${next}`;$('opponentArchetype').value=match?.opponentArchetype||'';setRadio('result',match?.result||'');const score=match?window.PTCGMatchStore.score(match):{wins:0,losses:0,draws:0};$('gameWins').value=score.wins;$('gameLosses').value=score.losses;$('gameDraws').value=score.draws;$('roundNotes').value=match?.notes||'';$('deleteRound').classList.toggle('hidden',!match);openSheet('roundBackdrop')}
function saveRound(event){event.preventDefault();const result=document.querySelector('input[name="result"]:checked')?.value;if(!['win','loss','draw'].includes(result)){toast('Choose Win, Loss or Draw');return}const used=participation.usedDeckRef||{};const existing=editingId?window.PTCGMatchStore.get(editingId):null;const playedAt=existing?.playedAt||now();const wins=Number($('gameWins').value)||0,losses=Number($('gameLosses').value)||0,draws=Number($('gameDraws').value)||0;if(wins+losses+draws<1){toast('Enter the game score');return}const scoreResult=wins>losses?'win':losses>wins?'loss':'draw';if(scoreResult!==result){toast('Match result and game score do not agree');return}const games=window.PTCGMatchStore.gamesFromScore(wins,losses,draws,null);window.PTCGMatchStore.put({...(existing||{}),id:existing?.id||undefined,source:'irl',playedAt,result,deckId:used.deckId||null,deckVersionId:used.deckVersionId||null,listHash:used.listHash||null,deckNameSnapshot:used.deckNameSnapshot||null,deckVersionLabelSnapshot:used.deckVersionLabelSnapshot||null,opponentArchetype:$('opponentArchetype').value.trim()||null,wentFirst:null,participationId:participation.id,eventId:participation.eventId,eventName:eventName(),roundLabel:$('roundLabel').value.trim()||`Round ${matches.length+1}`,notes:$('roundNotes').value.trim(),games});updateParticipation(row=>{row.tournamentDay={...(row.tournamentDay||{}),lastOpenedAt:now(),lastRoundAt:now()}});closeSheet('roundBackdrop');editingId=null;render();toast(existing?'Round corrected':'Round saved')}
function deleteRound(){if(!editingId)return;window.PTCGMatchStore.remove(editingId);updateParticipation(row=>{const prior=row.tournamentDay?.idCalc?.opponentRecords||{};const nextRecords={...prior};delete nextRecords[editingId];row.tournamentDay={...(row.tournamentDay||{}),lastOpenedAt:now(),idCalc:row.tournamentDay?.idCalc?{...row.tournamentDay.idCalc,opponentRecords:nextRecords}:undefined}});closeSheet('roundBackdrop');editingId=null;render();toast('Round deleted')}
function idState(){return participation.tournamentDay?.idCalc||{}}
function recordFields(prefix,value={}){return `<input data-id-record="${esc(prefix)}" data-part="wins" aria-label="Wins" type="number" min="0" inputmode="numeric" placeholder="W" value="${value.wins??''}"><input data-id-record="${esc(prefix)}" data-part="losses" aria-label="Losses" type="number" min="0" inputmode="numeric" placeholder="L" value="${value.losses??''}"><input data-id-record="${esc(prefix)}" data-part="draws" aria-label="Draws" type="number" min="0" inputmode="numeric" placeholder="D" value="${value.draws??''}">`}
function renderOpponentRecords(){const saved=idState().opponentRecords||{};$('opponentRecords').innerHTML=matches.map(match=>`<div class="record-entry"><span><strong>${esc(match.roundLabel||'Round')}</strong><small>${esc(match.opponentArchetype||'Opponent')}</small></span>${recordFields(match.id,saved[match.id]||{})}</div>`).join('')||'<div class="td-empty">Record a round first.</div>'}
function fillIdForm(){const saved=idState(),stats=record();$('idCurrent').innerHTML=`<strong>${stats.wins}-${stats.losses}-${stats.draws}</strong><span>${window.PTCGCutId.points(stats.wins,stats.draws)} pts now · ID gives ${window.PTCGCutId.points(stats.wins,stats.draws)+1} pts</span>`;$('idPlayers').value=saved.playerCount||participation.completion?.playerCount||'';$('idCut').value=saved.cutSize||8;$('idTotalRounds').value=saved.totalRounds||'';renderOpponentRecords();const next=saved.nextOpponentRecord||{};$('nextW').value=next.wins??'';$('nextL').value=next.losses??'';$('nextD').value=next.draws??'';setRadio('confidence',saved.confidence||'even');$('relevantRecords').value=(saved.relevantRecords||[]).join('\n');$('relevantComplete').checked=!!saved.relevantComplete;$('idResult').classList.add('hidden');$('idResult').innerHTML=''}
function openIdCalc(){if(!isStarted()||isCompleted()||!matches.length)return;fillIdForm();openSheet('idBackdrop')}
function readRecordInputs(){const out={};document.querySelectorAll('[data-id-record]').forEach(input=>{const id=input.dataset.idRecord,part=input.dataset.part;out[id]=out[id]||{};out[id][part]=input.value===''?null:Math.max(0,Number(input.value)||0)});return out}
function completeRecord(value){return value&&['wins','losses','draws'].every(key=>Number.isFinite(value[key]))&&(value.wins+value.losses+value.draws)>0}
function parseRelevant(text){return String(text||'').split(/\n+/).map(line=>line.trim()).filter(Boolean).map(line=>window.PTCGCutId.record(line)).filter(row=>row.wins+row.losses+row.draws>0)}
function saveIdCalc(event){event.preventDefault();const stats=record(),playerCount=Number($('idPlayers').value),cutSize=Number($('idCut').value),totalRounds=Number($('idTotalRounds').value);if(!Number.isInteger(playerCount)||playerCount<2){toast('Enter tournament player count');return}if(!Number.isInteger(cutSize)||cutSize<2||cutSize>playerCount){toast('Enter a valid cut size');return}if(!Number.isInteger(totalRounds)||totalRounds<stats.total+1){toast('Enter total Swiss rounds');return}const roundsRemaining=totalRounds-stats.total;if(roundsRemaining!==1){toast('ID Calc currently supports the final Swiss round');return}const opponentRecords=readRecordInputs(),knownOpponents=Object.values(opponentRecords).filter(completeRecord);const allOpponentsKnown=knownOpponents.length===matches.length;const nextOpponentRecord={wins:Math.max(0,Number($('nextW').value)||0),losses:Math.max(0,Number($('nextL').value)||0),draws:Math.max(0,Number($('nextD').value)||0)};if(nextOpponentRecord.wins+nextOpponentRecord.losses+nextOpponentRecord.draws!==stats.total){toast(`Next opponent record should total ${stats.total} rounds`);return}const relevantRecords=parseRelevant($('relevantRecords').value);const relevantComplete=$('relevantComplete').checked;const confidence=document.querySelector('input[name="confidence"]:checked')?.value||'even';const result=window.PTCGCutId.recommendation({wins:stats.wins,draws:stats.draws,cutSize,relevantRecords,nextOpponentRecord,opponentRecords:allOpponentsKnown?knownOpponents:[],confidence,relevantComplete});const state={playerCount,cutSize,totalRounds,opponentRecords,nextOpponentRecord,confidence,relevantRecords:relevantRecords.map(row=>`${row.wins}-${row.losses}-${row.draws}`),relevantComplete,updatedAt:now()};updateParticipation(row=>{row.tournamentDay={...(row.tournamentDay||{}),idCalc:state,lastOpenedAt:now()}});renderIdResult(result,{allOpponentsKnown,knownOpponents:knownOpponents.length,totalOpponents:matches.length,relevantCount:relevantRecords.length})}
function renderIdResult(result,meta){const el=$('idResult'),resistance=Number.isFinite(result.resistance)?`${Math.round(result.resistance*100)}%`:null;const cls=result.verdict==='id'?'id':result.verdict==='play'?'play':'close';const bullets=[];bullets.push(`ID → ${result.idPoints} pts.`);bullets.push(`${result.maxPlayersAbove} entered player${result.maxPlayersAbove===1?'':'s'} can finish above you; ${result.maxPlayersAtOrAbove} can finish at or above you under the one-round bound.`);if(result.relevantComplete)bullets.push('You marked the relevant standings set complete, so players below that set are treated as unable to reach your ID score.');else bullets.push(`This is a recommendation from the ${meta.relevantCount} relevant player records entered, not a mathematical lock.`);if(resistance)bullets.push(`Current Op Win % estimate: ${resistance}.`);else bullets.push(`Resistance not used: ${meta.knownOpponents}/${meta.totalOpponents} previous opponent records are complete.`);bullets.push(`Your matchup confidence implies roughly ${Math.round(result.matchupWinChance*100)}% win confidence for decision weighting only.`);el.className=`id-result ${cls}`;el.innerHTML=`<small>Recommendation</small><strong>${esc(result.label)}</strong><div>${bullets.map(text=>`<p>${esc(text)}</p>`).join('')}</div><span class="id-disclaimer">Hard points maths and your estimated resistance are shown separately; matchup confidence never changes the deterministic cut bound.</span>`}
function openCompletion(){if(isCompleted())return;if(!participation.usedDeckRef){toast('Choose the deck you used before completing');document.getElementById('tournamentDeckSlot')?.focus();return}const stats=record();$('completionRecord').innerHTML=`<strong>${stats.wins}-${stats.losses}-${stats.draws}</strong><span>${stats.total} rounds · ${esc(deckRefLabel(participation.usedDeckRef))}</span>`;$('placement').value=participation.completion?.placement||'';$('playerCount').value=participation.completion?.playerCount||idState().playerCount||'';$('completionNotes').value=participation.completion?.notes||'';openSheet('completionBackdrop')}
function completeEvent(event){event.preventDefault();const placement=Number($('placement').value),playerCount=Number($('playerCount').value);if(!Number.isFinite(placement)||placement<1){toast('Enter your final placement');return}if(!Number.isFinite(playerCount)||playerCount<1){toast('Enter the final player count');return}if(placement>playerCount){toast('Placement cannot exceed player count');return}const stats=record();updateParticipation(row=>{row.attendanceStatus='attended';row.completion={completedAt:now(),placement,playerCount,record:{wins:stats.wins,losses:stats.losses,draws:stats.draws},roundsCompleted:stats.total,usedDeckRef:row.usedDeckRef?{...row.usedDeckRef}:null,notes:$('completionNotes').value.trim()||null};row.tournamentDay=row.tournamentDay?{...row.tournamentDay,finishedAt:now()}:null});closeSheet('completionBackdrop');render();toast('Event completed')}
async function loadArchetypes(){try{await window.PTCGArchetypes?.load?.();window.PTCGArchetypes?.mergeSaved?.(decks.map(d=>d.archetype).filter(Boolean))}catch(error){console.warn('Archetype suggestions unavailable',error)}}
function bind(){$('addRound').addEventListener('click',()=>openRound());$('roundForm').addEventListener('submit',saveRound);$('deleteRound').addEventListener('click',deleteRound);$('openIdCalc').addEventListener('click',openIdCalc);$('idForm').addEventListener('submit',saveIdCalc);$('completeEvent').addEventListener('click',openCompletion);$('completionForm').addEventListener('submit',completeEvent);$('closeRoundSheet').addEventListener('click',()=>closeSheet('roundBackdrop'));$('closeIdCalc').addEventListener('click',()=>closeSheet('idBackdrop'));$('closeCompletion').addEventListener('click',()=>closeSheet('completionBackdrop'));['roundBackdrop','idBackdrop','completionBackdrop'].forEach(id=>$(id).addEventListener('click',event=>{if(event.target===$(id))closeSheet(id)}))}
async function init(){try{loadParticipation();ensureStarted();renderEvent();await window.PTCGDeckStore.open();decks=await window.PTCGDeckStore.all();if(participation.tournamentDay&&!participation.completion)updateParticipation(row=>{row.tournamentDay={...row.tournamentDay,lastOpenedAt:now()}});bind();render();$('workspace').classList.remove('hidden');loadArchetypes()}catch(error){console.error(error);$('fatal').textContent=error.message;$('fatal').classList.remove('hidden');setSaved('Unavailable')}}
init();
})();