(function(){
'use strict';
const $=id=>document.getElementById(id);let decks=[],active=null,activeTab='overview',dirty=false;
function toast(msg){const el=$('toast');el.textContent=msg;el.hidden=false;clearTimeout(el._t);el._t=setTimeout(()=>el.hidden=true,1800)}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function ago(ts){if(!ts)return '—';const m=Math.max(0,Math.floor((Date.now()-ts)/60000));if(m<1)return 'just now';if(m<60)return `${m}m ago`;const h=Math.floor(m/60);if(h<24)return `${h}h ago`;return `${Math.floor(h/24)}d ago`}
function parsed(){return window.PTCGDeckParser.parseDeck($('deckText').value||'')}
function summary(d){const p=window.PTCGDeckParser.parseDeck(d.rawText||'');return `${p.totalCards} cards · ${p.totals.pokemon} Pokémon · ${p.totals.trainers} Trainers · ${p.totals.energy} Energy · ${d.versions.length} version${d.versions.length===1?'':'s'} · ${ago(d.updatedAt)}`}
async function refresh(){decks=await window.PTCGDeckStore.all();renderLibrary()}
function renderLibrary(){const q=$('search').value.trim().toLowerCase(),sort=$('sort').value;let list=decks.filter(d=>(d.name||'').toLowerCase().includes(q));list.sort((a,b)=>sort==='name'?(a.name||'').localeCompare(b.name||''):(b.updatedAt||0)-(a.updatedAt||0));$('deckGrid').innerHTML=list.map(d=>`<article class="deck-card" tabindex="0" role="button" data-id="${esc(d.id)}"><div><h3>${esc(d.name)}</h3><p>${esc(summary(d))}</p></div><div class="deck-card-sprites">${(d.sprites||[]).filter(Boolean).map(s=>`<img src="${esc(s.spriteUrl||'')}" alt="${esc(s.name||'')}">`).join('')}</div></article>`).join('');$('emptyState').hidden=list.length>0}
function showLibrary(){active=null;dirty=false;$('libraryScreen').hidden=false;$('deckScreen').hidden=true;refresh()}
async function openDeck(id){const d=await window.PTCGDeckStore.get(id);if(!d)return;active=JSON.parse(JSON.stringify(d));$('libraryScreen').hidden=true;$('deckScreen').hidden=false;$('deckName').value=active.name;$('deckText').value=active.rawText||'';$('sprite1').value=active.sprites?.[0]?.name||'';$('sprite2').value=active.sprites?.[1]?.name||'';$('playtestButton').href=`../playtest/?deck=${encodeURIComponent(active.id)}`;dirty=false;setTab('overview');renderDeck()}
function renderDeck(){if(!active)return;const p=parsed();$('deckSummary').textContent=`${p.totalCards} cards · ${active.versions.length} version${active.versions.length===1?'':'s'}`;$('cardCountPill').textContent=`${p.totalCards} cards`;$('saveStatus').textContent=dirty?'Unsaved changes':`Saved ${ago(active.updatedAt)}`;$('deckHeaderSprites').innerHTML=(active.sprites||[]).filter(Boolean).map(s=>`<img src="${esc(s.spriteUrl||'')}" alt="${esc(s.name||'')}">`).join('');$('overviewMetrics').innerHTML=[['Cards',p.totalCards],['Pokémon',p.totals.pokemon],['Trainers',p.totals.trainers],['Energy',p.totals.energy]].map(([l,v])=>`<div class="metric-mini"><b>${v}</b><span>${l}</span></div>`).join('');renderVersions();renderPreview(p);renderOdds(p)}
function renderVersions(){const list=[...(active?.versions||[])].reverse();$('versionList').innerHTML=list.map(v=>`<div class="version-row ${v.id===active.currentVersionId?'current':''}"><div><b>${esc(v.label)}</b><small>${new Date(v.createdAt).toLocaleDateString()}${v.id===active.currentVersionId?' · current':''}</small></div><button type="button" data-load-version="${esc(v.id)}">Load</button></div>`).join('')}
function renderPreview(p){const sections=[['pokemon','Pokémon'],['trainers','Trainers'],['energy','Energy'],['unknown','Other']];$('parsedPreview').innerHTML=sections.filter(([k])=>p.sections[k]?.length).map(([k,label])=>`<div class="parsed-section"><h3>${label}</h3>${p.sections[k].map(c=>`<div class="parsed-card"><span>${esc(c.name)}</span><b>${c.count}</b></div>`).join('')}</div>`).join('')}
function cardOptions(p){const m=new Map();p.cards.forEach(c=>m.set(c.name,(m.get(c.name)||0)+c.count));return [...m.entries()].sort((a,b)=>a[0].localeCompare(b[0]))}
function renderOdds(p){const opts=cardOptions(p),sel=$('oddsCard'),prior=sel.value;sel.innerHTML=opts.map(([n,c])=>`<option value="${esc(n)}">${esc(n)} · ${c}</option>`).join('');if(opts.some(([n])=>n===prior))sel.value=prior;const name=sel.value;if(!name){$('oddsResults').innerHTML='<div class="app-empty">Add cards to the deck list to calculate odds.</div>';$('oddsDistribution').innerHTML='';return}const K=opts.find(([n])=>n===name)?.[1]||0,N=Math.max(p.totalCards,1),n=Math.min(Math.max(parseInt($('oddsSeen').value)||7,1),N),p0=hyper(N,K,n,0),atleast=1-p0,expected=n*K/N;$('oddsResults').innerHTML=`<div class="odds-result"><b>${pct(atleast)}</b><span>AT LEAST ONE</span></div><div class="odds-result"><b>${pct(p0)}</b><span>ZERO COPIES</span></div><div class="odds-result"><b>${expected.toFixed(2)}</b><span>EXPECTED COPIES</span></div>`;let rows='';for(let k=0;k<=Math.min(K,n);k++)rows+=`<div class="dist-row"><span>Exactly ${k}</span><b>${pct(hyper(N,K,n,k))}</b></div>`;$('oddsDistribution').innerHTML=rows}
function choose(n,k){if(k<0||k>n)return 0;k=Math.min(k,n-k);let r=1;for(let i=1;i<=k;i++)r=r*(n-k+i)/i;return r}
function hyper(N,K,n,k){const den=choose(N,n);return den?choose(K,k)*choose(N-K,n-k)/den:0}function pct(v){return `${(100*v).toFixed(1)}%`}
function setTab(tab){activeTab=tab;document.querySelectorAll('.deck-tabs button').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.tab===tab)));document.querySelectorAll('.deck-tab').forEach(s=>s.hidden=s.id!==`tab-${tab}`);if(tab==='odds')renderDeck()}
function markDirty(){if(!active)return;dirty=true;active.name=$('deckName').value.trim()||'Untitled deck';active.rawText=$('deckText').value||'';$('saveStatus').textContent='Unsaved changes';renderDeck()}
async function saveActive(){if(!active)return;active.name=$('deckName').value.trim()||'Untitled deck';active.rawText=$('deckText').value||'';active=await window.PTCGDeckStore.put(active);dirty=false;renderDeck();toast('Deck saved');refresh()}
async function createDeck(){const d=window.PTCGDeckStore.newDeck();await window.PTCGDeckStore.put(d);await refresh();openDeck(d.id)}
async function saveVersion(){if(!active)return;active.name=$('deckName').value.trim()||'Untitled deck';active.rawText=$('deckText').value||'';active=window.PTCGDeckStore.snapshot(active,$('versionLabel').value);active=await window.PTCGDeckStore.put(active);$('versionLabel').value='';dirty=false;renderDeck();toast('Version saved')}
async function duplicate(){if(!active)return;const d=JSON.parse(JSON.stringify(active));d.id=(crypto&&crypto.randomUUID)?crypto.randomUUID():`deck_${Date.now()}`;d.name=`${d.name} copy`;d.createdAt=Date.now();d.updatedAt=Date.now();d.versions=d.versions.map(v=>({...v,id:`${d.id}_${v.id}`}));d.currentVersionId=d.versions[d.versions.length-1]?.id||null;await window.PTCGDeckStore.put(d);closeSheets();await refresh();openDeck(d.id);toast('Deck duplicated')}
async function deleteActive(){if(!active||!confirm(`Delete ${active.name}?`))return;await window.PTCGDeckStore.remove(active.id);closeSheets();showLibrary();toast('Deck deleted')}
function download(filename,data){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}
function exportAll(){download(`ptcg-tools-decks-${new Date().toISOString().slice(0,10)}.json`,{kind:'ptcg-tools-decklists-backup',version:2,exportedAt:new Date().toISOString(),decks});closeSheets()}
function exportOne(){if(active)download(`${active.name.replace(/[^\w-]+/g,'_')}.json`,{kind:'ptcg-tools-decklists-backup',version:2,exportedAt:new Date().toISOString(),decks:[active]});closeSheets()}
async function importFile(file){try{const data=JSON.parse(await file.text()),list=Array.isArray(data?.decks)?data.decks:[];if(!list.length)throw new Error('No decks found');for(const item of list)await window.PTCGDeckStore.put(item);await refresh();toast(`Imported ${list.length} deck${list.length===1?'':'s'}`)}catch(e){toast(e.message||'Import failed')}}
async function copyText(){const t=$('deckText').value||'';try{await navigator.clipboard.writeText(t);toast('Deck list copied')}catch{toast('Clipboard unavailable')}}
function toLimitless(){const p=parsed();return p.cards.map(c=>`${c.count} ${c.name}${c.set?` ${c.set}`:''}${c.number?` ${c.number}`:''}`).join('\n')}
async function copyLimitless(){try{await navigator.clipboard.writeText(toLimitless());toast('Limitless list copied')}catch{toast('Clipboard unavailable')}}
function openSheet(id){$(id).hidden=false}function closeSheets(){document.querySelectorAll('.sheet').forEach(x=>x.hidden=true)}
async function selectSprite(slot,name){const key=name.trim().toLowerCase();if(!key){active.sprites[slot]=null;renderDeck();return}const sprite=await window.PTCGSprites.fetchSprite(key);if(sprite){active.sprites[slot]=sprite;$(slot===0?'sprite1':'sprite2').value=sprite.name;dirty=true;renderDeck()}}
function wireSprite(inputId,listId,slot){const input=$(inputId),list=$(listId);input.addEventListener('input',()=>{const q=input.value.trim();const rows=window.PTCGSprites.searchNamesSync(q,8);list.innerHTML=rows.map(r=>`<button type="button" data-sprite="${esc(r.name)}">${esc(r.name)}</button>`).join('');if(!q){active.sprites[slot]=null;dirty=true;renderDeck()}});list.addEventListener('click',e=>{const b=e.target.closest('[data-sprite]');if(!b)return;selectSprite(slot,b.dataset.sprite);list.innerHTML=''})}
function events(){
 $('newDeckTop').addEventListener('click',createDeck);$('emptyNew').addEventListener('click',createDeck);$('backDecks').addEventListener('click',showLibrary);$('search').addEventListener('input',renderLibrary);$('sort').addEventListener('change',renderLibrary);$('deckGrid').addEventListener('click',e=>{const c=e.target.closest('[data-id]');if(c)openDeck(c.dataset.id)});$('deckGrid').addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.closest('[data-id]')){e.preventDefault();openDeck(e.target.closest('[data-id]').dataset.id)}});document.querySelectorAll('.deck-tabs button').forEach(b=>b.addEventListener('click',()=>setTab(b.dataset.tab)));$('deckName').addEventListener('input',markDirty);$('deckText').addEventListener('input',markDirty);$('saveDeck').addEventListener('click',saveActive);$('saveList').addEventListener('click',saveActive);$('saveVersion').addEventListener('click',saveVersion);$('copyList').addEventListener('click',copyText);$('copyLimitless').addEventListener('click',copyLimitless);$('oddsCard').addEventListener('change',()=>renderOdds(parsed()));$('oddsSeen').addEventListener('input',()=>renderOdds(parsed()));$('versionList').addEventListener('click',e=>{const b=e.target.closest('[data-load-version]');if(!b)return;const v=active.versions.find(x=>x.id===b.dataset.loadVersion);if(v){$('deckText').value=v.rawText;active.currentVersionId=v.id;markDirty();setTab('list')}});$('libraryMenu').addEventListener('click',()=>openSheet('ioSheet'));$('deckMenu').addEventListener('click',()=>openSheet('deckSheet'));document.querySelectorAll('[data-close-sheet]').forEach(x=>x.addEventListener('click',closeSheets));$('exportDecks').addEventListener('click',exportAll);$('exportDeck').addEventListener('click',exportOne);$('duplicateDeck').addEventListener('click',duplicate);$('deleteDeck').addEventListener('click',deleteActive);$('importDecks').addEventListener('change',async e=>{const f=e.target.files?.[0];if(f)await importFile(f);e.target.value='';closeSheets()});wireSprite('sprite1','sprite1Suggestions',0);wireSprite('sprite2','sprite2Suggestions',1)
}
async function init(){await window.PTCGDeckStore.open();try{await window.PTCGSprites.getIndex()}catch{}events();await refresh();const q=new URLSearchParams(location.search).get('deck');if(q)openDeck(q)}
init().catch(e=>{console.error(e);toast('Decks failed to load')});
})();
