(() => {
  'use strict';
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
  let state=null,isAdmin=false,performance=null,registryDraft=null,formulaDraft=null;
  const pct=v=>`${(100*Number(v||0)).toFixed(1)}%`,ppDay=v=>`${(100*Number(v||0)).toFixed(2)}pp/day`;
  function ensureSections(){if($('sharedConfigSection'))return;const page=document.querySelector('.settings-page'),data=document.querySelector('[aria-labelledby="dataHeading"]');if(!page)return;const section=document.createElement('section');section.id='sharedConfigSection';section.className='settings-section';section.innerHTML='<div class="settings-section-head"><span class="settings-kicker">Shared configuration</span><h2>Formats & Blended model</h2><p>Published legality dates and the live Blended formula are common across Meta, What Should I Play, Event Prep and future legality checks.</p></div><div class="shared-config-card app-card"><div id="sharedConfigStatus">Loading shared configuration…</div><div id="formatAdminEditor" class="admin-config-editor"></div><div id="formulaAdminEditor" class="admin-config-editor"></div><p id="adminConfigMessage" class="admin-config-message" aria-live="polite"></p></div>';page.insertBefore(section,data||null)}
  async function loadPerformance(){try{const r=await fetch(new URL('../../data/meta/blended-performance.json',location.href),{cache:'no-store'});performance=r.ok?await r.json():null}catch{performance=null}}
  function publishedRegistry(){return state?.registries?.find(row=>row.status==='published')||null}
  function liveFormulaRow(){return state?.formulas?.find(row=>row.id===state?.live?.formula_id)||state?.formulas?.find(row=>row.status==='published')||null}
  function cleanSet(row,i){return {setCode:String(row.setCode||'').trim().toUpperCase(),setTitle:String(row.setTitle||'').trim(),releaseOrder:Number(row.releaseOrder||i+1),onlineLegalDate:row.onlineLegalDate||null,irlLegalDate:row.irlLegalDate||null,isRotationSet:!!row.isRotationSet,rotationLowerSetCode:row.isRotationSet?(String(row.rotationLowerSetCode||'').trim().toUpperCase()||null):null}}
  function statusHtml(){const registry=publishedRegistry(),sets=registry?.sets||[],online=window.PTCGFormatRuntime.resolveFormatAt(sets,'online'),irl=window.PTCGFormatRuntime.resolveFormatAt(sets,'irl'),formula=window.PTCGFormatRuntime.normaliseFormula(liveFormulaRow()||{});return `<div class="admin-status-grid"><div><span>Online format</span><b>${esc(online?.label||'Unavailable')}</b><small>${esc(online?.startDate||'')}</small></div><div><span>IRL format</span><b>${esc(irl?.label||'Unavailable')}</b><small>${esc(irl?.startDate||'')}</small></div><div><span>Live formula</span><b>${esc(formula.versionKey)}</b><small>${Math.round(100*formula.irlStartWeight)}% → −${(100*formula.irlDecayPerDay).toFixed(1)}pp/day → ${Math.round(100*formula.irlFloor)}%</small></div></div>`}
  function setRowsHtml(rows){return (rows||[]).sort((a,b)=>Number(a.releaseOrder)-Number(b.releaseOrder)).map((row,i)=>`<div class="set-admin-row" data-set-index="${i}"><input data-k="setCode" value="${esc(row.setCode||'')}" aria-label="Set code"><input data-k="setTitle" value="${esc(row.setTitle||'')}" aria-label="Set title"><input data-k="releaseOrder" type="number" min="1" value="${Number(row.releaseOrder||i+1)}" aria-label="Release order"><input data-k="onlineLegalDate" type="date" value="${esc(row.onlineLegalDate||'')}" aria-label="Online legal date"><input data-k="irlLegalDate" type="date" value="${esc(row.irlLegalDate||'')}" aria-label="IRL legal date"><label class="rotation-check"><input data-k="isRotationSet" type="checkbox" ${row.isRotationSet?'checked':''}><span>Rotation</span></label><input data-k="rotationLowerSetCode" value="${esc(row.rotationLowerSetCode||'')}" placeholder="New lower" aria-label="Rotation lower set code" ${row.isRotationSet?'':'disabled'}><button data-remove-set type="button" aria-label="Remove set">×</button></div>`).join('')}
  function readSetRows(){return [...document.querySelectorAll('.set-admin-row')].map((row,i)=>{const value=k=>row.querySelector(`[data-k="${k}"]`);return cleanSet({setCode:value('setCode')?.value,setTitle:value('setTitle')?.value,releaseOrder:value('releaseOrder')?.value,onlineLegalDate:value('onlineLegalDate')?.value||null,irlLegalDate:value('irlLegalDate')?.value||null,isRotationSet:value('isRotationSet')?.checked,rotationLowerSetCode:value('rotationLowerSetCode')?.value||null},i)}).filter(row=>row.setCode)}
  function bindSetRows(){document.querySelectorAll('[data-k="isRotationSet"]').forEach(input=>input.addEventListener('change',()=>{const lower=input.closest('.set-admin-row')?.querySelector('[data-k="rotationLowerSetCode"]');if(lower)lower.disabled=!input.checked}));document.querySelectorAll('[data-remove-set]').forEach(button=>button.addEventListener('click',()=>button.closest('.set-admin-row')?.remove()))}
  function renderRegistryAdmin(){const target=$('formatAdminEditor');if(!target)return;if(!isAdmin){target.innerHTML='<p class="admin-readonly">Published format dates are visible to everyone. Editing is restricted to the configured admin account.</p>';return}registryDraft=state.registries.find(row=>row.status==='draft')||registryDraft;if(!registryDraft){target.innerHTML='<button id="newRegistryDraft" class="settings-data-action" type="button">Edit format registry</button>';$('newRegistryDraft')?.addEventListener('click',()=>run('Creating draft…',async()=>{registryDraft=await window.PTCGFormatRuntime.createRegistryDraft();await reload()}));return}target.innerHTML=`<div class="admin-editor-head"><div><b>Registry draft v${Number(registryDraft.version_number)}</b><small>Changes do not affect the app until Publish.</small></div></div><div class="set-admin-labels"><span>Code</span><span>Set</span><span>Order</span><span>Online</span><span>IRL</span><span></span><span>Lower after rotation</span><span></span></div><div id="setAdminRows">${setRowsHtml(registryDraft.sets||[])}</div><button id="addSetRow" class="admin-secondary" type="button">+ Add set</button><label class="admin-note">Change note<textarea id="registryNotes" rows="2">${esc(registryDraft.notes||'')}</textarea></label><div class="admin-actions"><button id="saveRegistryDraft" class="admin-secondary" type="button">Save draft</button><button id="publishRegistry" class="admin-primary" type="button">Publish registry</button></div>`;bindSetRows();$('addSetRow')?.addEventListener('click',()=>{const rows=readSetRows();rows.push({setCode:'',setTitle:'',releaseOrder:Math.max(0,...rows.map(r=>r.releaseOrder))+1,onlineLegalDate:null,irlLegalDate:null,isRotationSet:false,rotationLowerSetCode:null});$('setAdminRows').innerHTML=setRowsHtml(rows);bindSetRows()});$('saveRegistryDraft')?.addEventListener('click',()=>run('Saving registry draft…',async()=>{registryDraft=await window.PTCGFormatRuntime.saveRegistryDraft(registryDraft.id,readSetRows(),$('registryNotes').value);await reload()}));$('publishRegistry')?.addEventListener('click',()=>run('Publishing registry…',async()=>{await window.PTCGFormatRuntime.saveRegistryDraft(registryDraft.id,readSetRows(),$('registryNotes').value);await window.PTCGFormatRuntime.publishRegistry(registryDraft.id);registryDraft=null;await window.PTCGFormatRuntime.refreshPublic();await reload()}))}
  function formulaValues(){return {irlStartWeight:Number($('formulaStart')?.value||0)/100,irlDecayPerDay:Number($('formulaDecay')?.value||0)/100,irlFloor:Number($('formulaFloor')?.value||0)/100,notes:$('formulaNotes')?.value||''}}
  function norm(rows){const map=new Map();for(const row of rows||[]){const name=String(row?.name||'').trim(),share=Math.max(0,Number(row?.share||0));if(!name||!share)continue;map.set(name,(map.get(name)||0)+share)}const total=[...map.values()].reduce((s,v)=>s+v,0);return total?[...map.entries()].map(([name,share])=>({name,share:share/total})):[]}
  function observationWeights(obs,f){if(!obs?.irlInput?.length||['rotation-online-only','online-only'].includes(obs.transitionState))return{irl:0,online:1};const start=Math.max(0,Math.min(1,f.irlStartWeight)),floor=Math.max(0,Math.min(start,f.irlFloor)),decay=Math.max(0,Math.min(1,f.irlDecayPerDay)),normal=Math.max(floor,Math.min(start,start-decay*Math.max(0,Number(obs.daysSinceMajor||0)))),irl=obs.transitionState==='previous-format-prior'?Math.min(normal,.25):normal;return{irl,online:1-irl}}
  function replayAccuracy(f){const complete=(performance?.snapshots||[]).filter(row=>row.actualField?.length&&row.onlineInput?.length);if(!complete.length)return null;let sum=0;for(const obs of complete){const w=observationWeights(obs,f),map=new Map();for(const row of norm(obs.irlInput))map.set(row.name,(map.get(row.name)||0)+row.share*w.irl);for(const row of norm(obs.onlineInput))map.set(row.name,(map.get(row.name)||0)+row.share*w.online);const pred=new Map(norm([...map.entries()].map(([name,share])=>({name,share}))).map(r=>[r.name,r.share])),actual=new Map(norm(obs.actualField).map(r=>[r.name,r.share])),names=new Set([...pred.keys(),...actual.keys()]),err=[...names].reduce((s,name)=>s+Math.abs((pred.get(name)||0)-(actual.get(name)||0)),0);sum+=Math.max(0,1-.5*err)}return sum/complete.length}
  function renderFormulaAdmin(){
    const target=$('formulaAdminEditor');if(!target)return;
    const live=window.PTCGFormatRuntime.normaliseFormula(liveFormulaRow()||{}),fit=performance?.fit||{};
    formulaDraft=state.formulas.find(row=>row.status==='draft')||formulaDraft;
    const evidence=Number(fit.dataPoints||0)?`Based on ${Number(fit.dataPoints)} Major-weekend observation${Number(fit.dataPoints)===1?'':'s'} · live ${pct(fit.liveAccuracy)} · best ${pct(fit.bestAccuracy)}`:'No completed Major-weekend observations yet.';
    let html=`<div class="formula-evidence"><b>${esc(live.versionKey)} live</b><span>${Math.round(100*live.irlStartWeight)}% start · ${ppDay(live.irlDecayPerDay)} · ${Math.round(100*live.irlFloor)}% floor</span><small>${esc(evidence)}</small></div>`;
    if(!isAdmin){target.innerHTML=html+'<p class="admin-readonly">Formula history is visible here; publishing controls are admin-only.</p>';return}
    if(!formulaDraft)html+='<button id="newFormulaDraft" class="settings-data-action" type="button">New formula draft</button>';
    else{
      const f=window.PTCGFormatRuntime.normaliseFormula(formulaDraft);
      html+=`<div class="formula-admin-grid"><label>IRL start %<input id="formulaStart" type="number" min="0" max="100" step="0.1" value="${(100*f.irlStartWeight).toFixed(1)}"></label><label>Decay pp/day<input id="formulaDecay" type="number" min="0" max="100" step="0.01" value="${(100*f.irlDecayPerDay).toFixed(2)}"></label><label>IRL floor %<input id="formulaFloor" type="number" min="0" max="100" step="0.1" value="${(100*f.irlFloor).toFixed(1)}"></label></div><p class="fixed-policy">Fixed transition policy: previous-format IRL cap 25%; rotation prior-format weight 0%.</p><label class="admin-note">Change note<textarea id="formulaNotes" rows="2">${esc(f.notes||'')}</textarea></label><div class="admin-actions">${fit.bestFormula&&Number(fit.dataPoints||0)?'<button id="useBestFit" class="admin-secondary" type="button">Use best fit</button>':''}<button id="saveFormulaDraft" class="admin-secondary" type="button">Save draft</button><button id="publishFormula" class="admin-primary" type="button">Publish formula</button></div>`;
    }
    const history=state.formulas.filter(row=>row.status==='published').map(row=>{const f=window.PTCGFormatRuntime.normaliseFormula(row),active=row.id===state.live?.formula_id,disabled=formulaDraft?' disabled title="Finish the current draft first"':'';return `<div class="formula-history-row"><span><b>${esc(f.versionKey)}</b><small>${Math.round(100*f.irlStartWeight)}% · ${ppDay(f.irlDecayPerDay)} · ${Math.round(100*f.irlFloor)}%</small></span>${active?'<strong>Live</strong>':`<button type="button" data-draft-from="${esc(row.id)}"${disabled}>Draft from this</button>`}</div>`}).join('');
    html+=`<div class="formula-history"><span class="settings-kicker">Formula history</span>${history}</div>`;
    target.innerHTML=html;
    $('newFormulaDraft')?.addEventListener('click',()=>run('Creating formula draft…',async()=>{formulaDraft=await window.PTCGFormatRuntime.createFormulaDraft(live);await reload()}));
    $('useBestFit')?.addEventListener('click',()=>{const f=fit.bestFormula;$('formulaStart').value=(100*Number(f.irlStartWeight)).toFixed(1);$('formulaDecay').value=(100*Number(f.irlDecayPerDay)).toFixed(2);$('formulaFloor').value=(100*Number(f.irlFloor)).toFixed(1)});
    $('saveFormulaDraft')?.addEventListener('click',()=>run('Saving formula draft…',async()=>{formulaDraft=await window.PTCGFormatRuntime.saveFormulaDraft(formulaDraft.id,formulaValues());await reload()}));
    $('publishFormula')?.addEventListener('click',()=>run('Publishing formula…',async()=>{const proposed=formulaValues(),liveAcc=replayAccuracy(live),proposedAcc=replayAccuracy(proposed);if(liveAcc!=null&&proposedAcc!=null&&proposedAcc<liveAcc&&!confirm(`This formula backtests worse than the current live formula (${pct(proposedAcc)} vs ${pct(liveAcc)}). Publish anyway?`))return;await window.PTCGFormatRuntime.saveFormulaDraft(formulaDraft.id,proposed);await window.PTCGFormatRuntime.publishFormula(formulaDraft.id);formulaDraft=null;await window.PTCGFormatRuntime.refreshPublic();await reload()}));
    document.querySelectorAll('[data-draft-from]').forEach(button=>button.addEventListener('click',()=>run('Creating formula draft…',async()=>{const row=state.formulas.find(item=>item.id===button.dataset.draftFrom);if(!row)throw new Error('Historical formula not found.');const f=window.PTCGFormatRuntime.normaliseFormula(row);formulaDraft=await window.PTCGFormatRuntime.createFormulaDraft({irlStartWeight:f.irlStartWeight,irlDecayPerDay:f.irlDecayPerDay,irlFloor:f.irlFloor,notes:`Drafted from ${f.versionKey}.`});await reload()})));
  }
  async function run(message,fn){const status=$('adminConfigMessage');if(status){status.textContent=message;status.classList.remove('is-error')}try{await fn();if(status)status.textContent='Saved.'}catch(error){if(status){status.textContent=error?.message||'Admin change failed.';status.classList.add('is-error')}}}
  async function reload(){state=await window.PTCGFormatRuntime.adminState();render()}
  function render(){if($('sharedConfigStatus'))$('sharedConfigStatus').innerHTML=statusHtml();renderRegistryAdmin();renderFormulaAdmin()}
  async function init(){ensureSections();if(!window.PTCGFormatRuntime)return;await Promise.all([loadPerformance(),window.PTCGFormatRuntime.ready?.()]);try{state=await window.PTCGFormatRuntime.adminState();isAdmin=await window.PTCGFormatRuntime.isAdmin()}catch(error){console.warn('Shared config unavailable',error);state={registries:[],formulas:[],live:null};isAdmin=false}render()}
  ['ptcg:auth-change','ptcg:format-config'].forEach(name=>window.addEventListener(name,()=>init()));init();
})();