(function(){
'use strict';
const $=id=>document.getElementById(id);
const DB_NAME='ptcg-tools-db',STORE='tournaments';
let db=null,tournaments=[],current=null,selectedTab='run',timerTick=null;
const uid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const now=()=>new Date().toISOString();
function ensureTournamentStore(d){if(!d.objectStoreNames.contains(STORE)){const s=d.createObjectStore(STORE,{keyPath:'id'});s.createIndex('updatedAt','updatedAt',{unique:false});s.createIndex('name','name',{unique:false})}}
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME);r.onerror=()=>reject(r.error);r.onsuccess=()=>{const currentDb=r.result;if(currentDb.objectStoreNames.contains(STORE)){resolve(currentDb);return}const nextVersion=currentDb.version+1;currentDb.close();const upgrade=indexedDB.open(DB_NAME,nextVersion);upgrade.onupgradeneeded=()=>ensureTournamentStore(upgrade.result);upgrade.onsuccess=()=>resolve(upgrade.result);upgrade.onerror=()=>reject(upgrade.error);upgrade.onblocked=()=>reject(new Error('Tournament database upgrade blocked'))}})}
function tx(mode='readonly'){return db.transaction(STORE,mode).objectStore(STORE)}
function all(){return new Promise((res,rej)=>{const r=tx().getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
function put(v){return new Promise((res,rej)=>{v.updatedAt=now();const r=tx('readwrite').put(v);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function del(id){return new Promise((res,rej)=>{const r=tx('readwrite').delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function blank(){return{id:uid(),name:'New tournament',format:'Bo3',type:'Casual',pairingMode:'swiss',roundsPlanned:5,topCut:{size:0,started:false},players:[],rounds:[],timer:{durationSec:50*60,remainingSec:50*60,endsAt:null,running:false},createdAt:now(),updatedAt:now()}}
function swissRounds(){return(current?.rounds||[]).filter(r=>(r.phase||'swiss')==='swiss')}
function complete(m){return !!m.bye||['P1','P2','T'].includes(m.result)}
function completedRounds(){return swissRounds().filter(r=>r.matches.every(complete))}
function matches(){return completedRounds().flatMap(r=>r.matches)}
function rec(id){let w=0,l=0,d=0,pts=0;for(const m of matches()){if(m.p1!==id&&m.p2!==id)continue;if(m.bye){w++;pts+=3;continue}if(m.result==='T'){d++;pts++;continue}const win=(m.result==='P1'&&m.p1===id)||(m.result==='P2'&&m.p2===id);if(win){w++;pts+=3}else l++}return{w,l,d,pts}}
function opps(id){return matches().filter(m=>!m.bye&&(m.p1===id||m.p2===id)).map(m=>m.p1===id?m.p2:m.p1)}
function wp(id){const r=rec(id),n=r.w+r.l+r.d;return Math.max(.25,n?r.w/n:0)}
function owp(id){const o=opps(id);return o.length?o.reduce((s,x)=>s+wp(x),0)/o.length:0}
function oowp(id){const o=opps(id);return o.length?o.reduce((s,x)=>s+owp(x),0)/o.length:0}
function standings(){return(current?.players||[]).map(p=>({...p,...rec(p.id),owp:owp(p.id),oowp:oowp(p.id)})).sort((a,b)=>b.pts-a.pts||b.owp-a.owp||b.oowp-a.oowp||a.name.localeCompare(b.name))}
function played(a,b){return matches().some(m=>!m.bye&&((m.p1===a&&m.p2===b)||(m.p1===b&&m.p2===a)))}
function hadBye(id){return matches().some(m=>m.bye&&m.p1===id)}
function makePairings(){const rows=standings();const pool=rows.map(r=>r.id),out=[];if(pool.length%2){let i=pool.length-1;while(i>0&&hadBye(pool[i]))i--;const bye=pool.splice(i,1)[0];out.push({p1:bye,p2:null,result:'P1',bye:true})}while(pool.length){const a=pool.shift();let j=pool.findIndex(b=>!played(a,b));if(j<0)j=0;const b=pool.splice(j,1)[0];out.push({p1:a,p2:b,result:null,bye:false})}return out}
function pName(id){return current?.players?.find(p=>p.id===id)?.name||'Player'}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmt(sec){sec=Math.max(0,Math.floor(sec||0));return `${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function remaining(){if(!current?.timer)return 0;if(current.timer.running&&current.timer.endsAt)return Math.max(0,Math.ceil((current.timer.endsAt-Date.now())/1000));return current.timer.remainingSec||current.timer.durationSec||0}
async function save(){if(!current)return;await put(current);const i=tournaments.findIndex(t=>t.id===current.id);if(i>=0)tournaments[i]=current;else tournaments.unshift(current)}
function setTab(tab){selectedTab=tab;document.querySelectorAll('[data-tm-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tmTab===tab));document.querySelectorAll('.tm-pane').forEach(p=>p.classList.toggle('hidden',p.id!==`tm-${tab}`));renderPane()}
function renderLibrary(){const host=$('tmLibraryList');host.innerHTML='';const sorted=[...tournaments].sort((a,b)=>String(b.updatedAt||'').localeCompare(String(a.updatedAt||'')));if(!sorted.length){host.innerHTML='<div class="tm-empty">No organiser tournaments yet.</div>';return}for(const t of sorted){const r=(t.players||[]).length;const rounds=(t.rounds||[]).filter(x=>(x.phase||'swiss')==='swiss').length;const btn=document.createElement('button');btn.className='tm-library-row';btn.type='button';btn.innerHTML=`<span><b>${esc(t.name||'Tournament')}</b><small>${r} players · ${rounds}/${Number(t.roundsPlanned||0)} Swiss · ${esc(t.format||'')}</small></span><span>›</span>`;btn.onclick=()=>openTournament(t.id);host.appendChild(btn)}}
function renderHeader(){if(!current)return;$('tmTitle').textContent=current.name||'Tournament';$('tmMeta').textContent=`${current.players.length} players · ${current.format||'Bo3'} · ${current.type||'Other'}`;$('tmTimer').textContent=fmt(remaining());$('tmTimerToggle').textContent=current.timer?.running?'Pause':'Start'}
function renderRun(){const host=$('tmRun');const rounds=swissRounds();let html='';if(!rounds.length)html='<div class="tm-empty">Add players, then generate Round 1.</div>';for(const r of rounds){html+=`<section class="tm-round"><div class="tm-round-head"><b>Round ${r.roundNumber}</b><small>${r.matches.every(complete)?'Complete':'In progress'}</small></div>`;r.matches.forEach((m,idx)=>{if(m.bye){html+=`<div class="tm-match tm-match-bye"><strong>${esc(pName(m.p1))}</strong><span class="tm-result-pill">BYE</span></div>`}else{const p1=esc(pName(m.p1)),p2=esc(pName(m.p2));html+=`<div class="tm-match tm-match-picker"><div class="tm-result-choices"><button type="button" data-result="P1" data-r="${r.roundNumber}" data-m="${idx}" class="${m.result==='P1'?'active':''}">${p1}</button><span class="tm-vs">vs</span><button type="button" data-result="P2" data-r="${r.roundNumber}" data-m="${idx}" class="${m.result==='P2'?'active':''}">${p2}</button><button type="button" data-result="T" data-r="${r.roundNumber}" data-m="${idx}" class="tm-draw ${m.result==='T'?'active':''}">Tie</button></div></div>`}});html+='</section>'}host.innerHTML=html;host.querySelectorAll('[data-result]').forEach(b=>b.onclick=async()=>{const r=rounds.find(x=>x.roundNumber===Number(b.dataset.r));if(!r)return;r.matches[Number(b.dataset.m)].result=b.dataset.result;await save();renderRun();renderStandings()});const can=current.players.length>=2&&(rounds.length===0||rounds[rounds.length-1].matches.every(complete))&&rounds.length<Number(current.roundsPlanned||5);$('tmNextRound').disabled=!can;$('tmNextRound').textContent=rounds.length?`Generate Round ${rounds.length+1}`:'Generate Round 1'}
function renderPlayers(){const host=$('tmPlayers');host.innerHTML=(current.players||[]).map(p=>`<div class="tm-player"><span>${esc(p.name)}</span><button type="button" data-remove-player="${p.id}" aria-label="Remove ${esc(p.name)}">×</button></div>`).join('')||'<div class="tm-empty">No players yet.</div>';host.querySelectorAll('[data-remove-player]').forEach(b=>b.onclick=async()=>{if(swissRounds().length)return alert('Players cannot be removed after Swiss has started.');current.players=current.players.filter(p=>p.id!==b.dataset.removePlayer);await save();renderPlayers();renderHeader()})}
function renderStandings(){const host=$('tmStandings');const rows=standings();host.innerHTML=rows.length?rows.map((r,i)=>`<div class="tm-standing"><b>${i+1}</b><span>${esc(r.name)}<small>${r.w}-${r.l}-${r.d}</small></span><strong>${r.pts}</strong><small>${(r.owp*100).toFixed(1)}%</small></div>`).join(''):'<div class="tm-empty">Standings appear after players are added.</div>'}
function renderPane(){if(!current)return;if(selectedTab==='run')renderRun();else if(selectedTab==='players')renderPlayers();else renderStandings();renderHeader()}
function showLibrary(){current=null;$('tmLibrary').classList.remove('hidden');$('tmWorkspace').classList.add('hidden');renderLibrary()}
function openTournament(id){current=tournaments.find(t=>t.id===id)||null;if(!current)return;current.timer=current.timer||{durationSec:(current.format==='Bo1'?1800:3000),remainingSec:(current.format==='Bo1'?1800:3000),endsAt:null,running:false};$('tmLibrary').classList.add('hidden');$('tmWorkspace').classList.remove('hidden');setTab('run')}
async function createTournament(){const t=blank();tournaments.unshift(t);current=t;await save();openTournament(t.id);openSettings()}
function ensureSettingsOptions(){const type=$('tmType'),cut=$('tmCut');if(type&&!type.querySelector('option[value="Casual"]'))type.insertAdjacentHTML('afterbegin','<option value="Casual">Casual</option>');if(cut&&!cut.querySelector('option[value="0"]'))cut.insertAdjacentHTML('afterbegin','<option value="0">No top cut</option>')}
function openSettings(){ensureSettingsOptions();$('tmName').value=current.name||'';$('tmFormat').value=current.format||'Bo3';$('tmType').value=current.type||'Casual';$('tmRounds').value=current.roundsPlanned||5;$('tmCut').value=String(current.topCut?.size??0);$('tmSettings').classList.remove('hidden')}
function closeSettings(){$('tmSettings').classList.add('hidden')}
async function saveSettings(){current.name=$('tmName').value.trim()||'Tournament';current.format=$('tmFormat').value;current.type=$('tmType').value;current.roundsPlanned=Math.max(1,Number($('tmRounds').value)||5);current.topCut=current.topCut||{};current.topCut.size=Math.max(0,Number($('tmCut').value)||0);if(!current.timer?.running){const duration=current.format==='Bo1'?1800:3000;current.timer={...(current.timer||{}),durationSec:duration,remainingSec:duration,endsAt:null,running:false}}await save();closeSettings();renderHeader();renderLibrary()}
async function nextRound(){if(!current)return;const rounds=swissRounds();if(rounds.length&& !rounds[rounds.length-1].matches.every(complete))return;current.rounds.push({phase:'swiss',roundNumber:rounds.length+1,label:`Round ${rounds.length+1}`,matches:makePairings()});await save();renderRun();renderStandings()}
async function addPlayer(){const input=$('tmPlayerName'),name=input.value.trim();if(!name)return;if(swissRounds().length)return alert('Add players before Swiss starts.');current.players.push({id:uid(),name});input.value='';await save();renderPlayers();renderHeader()}
async function toggleTimer(){if(!current)return;current.timer=current.timer||{};if(current.timer.running){current.timer.remainingSec=remaining();current.timer.running=false;current.timer.endsAt=null}else{let rem=remaining();if(rem<=0)rem=current.timer.durationSec||3000;current.timer.remainingSec=rem;current.timer.running=true;current.timer.endsAt=Date.now()+rem*1000}await save();renderHeader()}
async function resetTimer(){if(!current)return;current.timer.running=false;current.timer.endsAt=null;current.timer.remainingSec=current.timer.durationSec||(current.format==='Bo1'?1800:3000);await save();renderHeader()}
async function deleteCurrent(){if(!current||!confirm(`Delete ${current.name}?`))return;const id=current.id;await del(id);tournaments=tournaments.filter(t=>t.id!==id);closeSettings();showLibrary()}
function injectPickerStyles(){if(document.getElementById('tmPickerStyles'))return;const style=document.createElement('style');style.id='tmPickerStyles';style.textContent='.tm-match-picker{display:block;padding:10px 12px}.tm-result-choices{display:grid;grid-template-columns:minmax(0,1fr) auto minmax(0,1fr) auto;align-items:center;gap:7px;width:100%}.tm-result-choices button{min-width:0;min-height:42px;border:1px solid var(--app-border);border-radius:10px;background:#fff;color:var(--app-text);font:inherit;font-size:12px;font-weight:800;padding:8px 10px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.tm-result-choices button.active{background:var(--app-blue);border-color:var(--app-blue);color:#fff}.tm-result-choices .tm-draw{min-width:52px;color:var(--app-blue)}.tm-vs{color:var(--app-muted);font-size:10px;font-weight:800;text-transform:lowercase}.tm-match-bye strong{font-size:12px}@media(max-width:390px){.tm-result-choices{grid-template-columns:minmax(0,1fr) auto minmax(0,1fr);gap:6px}.tm-result-choices .tm-draw{grid-column:1/-1;min-height:34px}.tm-vs{font-size:9px}}';document.head.appendChild(style)}
async function init(){injectPickerStyles();ensureSettingsOptions();db=await openDB();tournaments=await all();$('tmNew').onclick=createTournament;$('tmBack').onclick=showLibrary;$('tmSettingsOpen').onclick=openSettings;$('tmSettingsClose').onclick=closeSettings;$('tmSettingsSave').onclick=saveSettings;$('tmDelete').onclick=deleteCurrent;$('tmNextRound').onclick=nextRound;$('tmAddPlayer').onclick=addPlayer;$('tmPlayerName').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();addPlayer()}});$('tmTimerToggle').onclick=toggleTimer;$('tmTimerReset').onclick=resetTimer;document.querySelectorAll('[data-tm-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tmTab));timerTick=setInterval(()=>{if(current?.timer?.running){if(remaining()<=0){current.timer.running=false;current.timer.remainingSec=0;current.timer.endsAt=null;save()}renderHeader()}},500);renderLibrary()}
init().catch(err=>{console.error(err);$('tmLibraryList').innerHTML='<div class="tm-empty">Tournament Manager could not load.</div>'});
})();