let DATA = null;
let CACHE = null;
let FILTERED_TOURNAMENTS = [];
let loading = false;
const CACHE_URL = '../../data/meta/standard.json';
const $ = id => document.getElementById(id);
const fmt = n => Number(n || 0).toFixed(1) + '%';

function setStatus(text) { $('status').textContent = text; }
function escapeHtml(value) {
  return String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
}
function short(value) {
  const s = String(value || '');
  return escapeHtml(s.length > 16 ? s.slice(0, 14) + '…' : s);
}
function setBusy(value) {
  loading = value;
  $('apply').disabled = value;
  $('refresh').disabled = value;
}

function setupTabs() {
  document.querySelectorAll('.tab').forEach(button => {
    button.addEventListener('click', () => {
      document.querySelectorAll('.tab').forEach(x => x.classList.remove('active'));
      document.querySelectorAll('.tabpane').forEach(x => x.classList.add('hidden'));
      button.classList.add('active');
      $(button.dataset.tab).classList.remove('hidden');
    });
  });
}

async function fetchSharedCache(force = false) {
  const url = force ? `${CACHE_URL}?v=${Date.now()}` : CACHE_URL;
  const response = await fetch(url, { cache: force ? 'no-store' : 'default' });
  if (!response.ok) throw new Error(`Shared meta cache ${response.status}`);
  const payload = await response.json();
  if (!payload || !Array.isArray(payload.tournaments)) throw new Error('Shared meta cache is invalid');
  CACHE = payload;
}

function applyFilters() {
  if (!CACHE) return;
  const days = Number($('days').value);
  const requestedMinPlayers = Number($('minPlayers').value);
  const cacheFloor = Number(CACHE.minTournamentSize || 0);
  const minPlayers = Math.max(requestedMinPlayers, cacheFloor);
  const cutoff = Date.now() - days * 86400000;

  FILTERED_TOURNAMENTS = CACHE.tournaments.filter(t => {
    const date = new Date(t.date).getTime();
    return Number.isFinite(date) && date >= cutoff && Number(t.players || 0) >= minPlayers;
  });

  DATA = MetaEngine.aggregate(FILTERED_TOURNAMENTS);
  render();

  const generated = CACHE.generatedAt ? new Date(CACHE.generatedAt).toLocaleString() : 'not generated yet';
  const floorNote = requestedMinPlayers < cacheFloor ? ` • cache minimum ${cacheFloor}` : '';
  setStatus(`Shared cache • ${DATA.tournamentCount} tournaments • updated ${generated}${floorNote}`);
}

async function loadShared(force = false) {
  if (loading) return;
  setBusy(true);
  try {
    setStatus(force ? 'Reloading shared data…' : 'Loading shared data…');
    await fetchSharedCache(force);
    if (!CACHE.generatedAt || !CACHE.tournaments.length) {
      FILTERED_TOURNAMENTS = [];
      DATA = MetaEngine.aggregate([]);
      render();
      setStatus('Shared cache is being generated by GitHub Actions. Try Reload data shortly.');
      return;
    }
    applyFilters();
  } catch (error) {
    console.error(error);
    setStatus('Error: ' + error.message);
  } finally {
    setBusy(false);
  }
}

function render() {
  const archetypes = DATA?.archetypes || [];
  $('summary').innerHTML = `
    <div class="metric"><b>${DATA?.tournamentCount || 0}</b><span>Tournaments</span></div>
    <div class="metric"><b>${DATA?.totalPlayers || 0}</b><span>Deck entries</span></div>
    <div class="metric"><b>${DATA?.matches || 0}</b><span>Matches</span></div>
    <div class="metric"><b>${archetypes.length}</b><span>Archetypes</span></div>`;

  $('metaBody').innerHTML = archetypes.map(row => `
    <tr class="click" data-archetype="${escapeHtml(row.name)}">
      <td><b>${escapeHtml(row.name)}</b></td><td>${row.players}</td><td>${fmt(row.share)}</td>
      <td>${row.wins}</td><td>${row.losses}</td><td>${row.ties}</td><td>${fmt(row.winRate)}</td>
    </tr>`).join('');

  document.querySelectorAll('#metaBody tr').forEach(row => row.addEventListener('click', () => openArchetype(row.dataset.archetype)));
  $('archSelect').innerHTML = archetypes.map(row => `<option>${escapeHtml(row.name)}</option>`).join('');
  $('archSelect').onchange = () => renderArchetype($('archSelect').value);
  renderMatrix();

  if (archetypes[0]) renderArchetype(archetypes[0].name);
  else {
    $('archTitle').textContent = 'No archetype data';
    $('archSummary').innerHTML = '';
    $('trendSummary').innerHTML = '';
    $('trendChart').innerHTML = '<div class="chart-empty">No data for these filters.</div>';
    $('archMatchups').innerHTML = '';
    $('archResults').innerHTML = '';
  }
}

function renderMatrix() {
  const minMatches = Number($('minMatches').value);
  const top = (DATA?.archetypes || []).slice(0, 15);
  let html = '<table><thead><tr><th>Deck</th>' + top.map(x => `<th title="${escapeHtml(x.name)}">${short(x.name)}</th>`).join('') + '</tr></thead><tbody>';
  for (const row of top) {
    html += `<tr><th>${escapeHtml(row.name)}</th>`;
    for (const col of top) {
      const matchup = DATA.matchups.get(`${row.name}|||${col.name}`);
      const decisive = matchup ? matchup.wins + matchup.losses : 0;
      const value = matchup && matchup.games >= minMatches && decisive > 0 ? fmt(100 * matchup.wins / decisive) : '—';
      const title = matchup ? `${matchup.wins}-${matchup.losses}-${matchup.ties} (${matchup.games} games)` : '';
      html += `<td title="${title}">${value}</td>`;
    }
    html += '</tr>';
  }
  $('matrix').innerHTML = html + '</tbody></table>';
}

function archetypeOf(standing) { return standing?.deck?.name || 'Unknown'; }

function trendPoints(name) {
  const days = Number($('days').value);
  const rollingDays = days <= 14 ? 3 : 7;
  const now = new Date();
  now.setHours(23, 59, 59, 999);
  const start = new Date(now.getTime() - (days - 1) * 86400000);
  const points = [];

  for (let i = 0; i < days; i++) {
    const end = new Date(start.getTime() + i * 86400000);
    end.setHours(23, 59, 59, 999);
    const windowStart = new Date(end.getTime() - (rollingDays - 1) * 86400000);
    windowStart.setHours(0, 0, 0, 0);
    let total = 0;
    let target = 0;

    for (const t of FILTERED_TOURNAMENTS) {
      const ts = new Date(t.date).getTime();
      if (ts < windowStart.getTime() || ts > end.getTime()) continue;
      for (const standing of t.standings || []) {
        const arch = archetypeOf(standing);
        if (arch === 'Unknown') continue;
        total += 1;
        if (arch === name) target += 1;
      }
    }

    if (total > 0) points.push({ date: end, share: 100 * target / total, total, target });
  }
  return { points, rollingDays };
}

function renderTrend(name) {
  const { points, rollingDays } = trendPoints(name);
  if (points.length < 2) {
    $('trendSummary').textContent = `${rollingDays}-day rolling share`;
    $('trendChart').innerHTML = '<div class="chart-empty">Not enough tournament data to draw a trend.</div>';
    return;
  }

  const first = points[0].share;
  const latest = points[points.length - 1].share;
  const change = latest - first;
  $('trendSummary').innerHTML = `<b>${fmt(latest)}</b><span>${change >= 0 ? '+' : ''}${change.toFixed(1)} pp over period • ${rollingDays}-day rolling</span>`;

  const W = 820, H = 250, L = 48, R = 18, T = 18, B = 34;
  const plotW = W - L - R, plotH = H - T - B;
  const maxValue = Math.max(5, ...points.map(p => p.share));
  const yMax = Math.ceil((maxValue * 1.12) / 5) * 5;
  const x = i => L + (i / Math.max(1, points.length - 1)) * plotW;
  const y = v => T + plotH - (v / yMax) * plotH;
  const poly = points.map((p, i) => `${x(i).toFixed(1)},${y(p.share).toFixed(1)}`).join(' ');
  const grid = [0, .25, .5, .75, 1].map(frac => {
    const value = yMax * frac;
    const yy = y(value);
    return `<line x1="${L}" y1="${yy}" x2="${W-R}" y2="${yy}" class="chart-grid"/><text x="${L-8}" y="${yy+4}" text-anchor="end" class="chart-label">${value.toFixed(0)}%</text>`;
  }).join('');
  const dots = points.map((p, i) => `<circle cx="${x(i)}" cy="${y(p.share)}" r="3" class="chart-dot"><title>${p.date.toLocaleDateString()}: ${p.share.toFixed(1)}% (${p.target}/${p.total})</title></circle>`).join('');
  const firstDate = points[0].date.toLocaleDateString(undefined, { month:'short', day:'numeric' });
  const lastDate = points[points.length-1].date.toLocaleDateString(undefined, { month:'short', day:'numeric' });

  $('trendChart').innerHTML = `<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${escapeHtml(name)} meta share trend">${grid}<polyline points="${poly}" class="chart-line"/>${dots}<text x="${L}" y="${H-8}" class="chart-label">${escapeHtml(firstDate)}</text><text x="${W-R}" y="${H-8}" text-anchor="end" class="chart-label">${escapeHtml(lastDate)}</text></svg>`;
}

function renderArchetype(name) {
  const archetype = DATA.archetypes.find(x => x.name === name);
  if (!archetype) return;
  $('archTitle').textContent = name;
  $('archSelect').value = name;
  $('archSummary').innerHTML = `
    <div class="metric"><b>${archetype.players}</b><span>Players</span></div>
    <div class="metric"><b>${fmt(archetype.share)}</b><span>Meta share</span></div>
    <div class="metric"><b>${fmt(archetype.winRate)}</b><span>Win rate</span></div>
    <div class="metric"><b>${archetype.wins}-${archetype.losses}-${archetype.ties}</b><span>Record</span></div>`;

  renderTrend(name);

  const matchups = [...DATA.matchups.values()].filter(x => x.a === name).sort((a, b) => b.games - a.games).slice(0, 20);
  $('archMatchups').innerHTML = '<table><thead><tr><th>Opponent</th><th>Games</th><th>Record</th><th>Win %</th></tr></thead><tbody>' +
    matchups.map(m => { const d = m.wins + m.losses; return `<tr><td>${escapeHtml(m.b)}</td><td>${m.games}</td><td>${m.wins}-${m.losses}-${m.ties}</td><td>${d ? fmt(100 * m.wins / d) : '—'}</td></tr>`; }).join('') + '</tbody></table>';

  const results = DATA.results.filter(x => x.archetype === name).sort((a, b) => a.placing - b.placing || new Date(b.date) - new Date(a.date)).slice(0, 20);
  $('archResults').innerHTML = '<table><thead><tr><th>Place</th><th>Player</th><th>Event</th><th>Record</th></tr></thead><tbody>' +
    results.map(r => `<tr><td>${r.placing}/${r.players}</td><td>${escapeHtml(r.player)}</td><td>${escapeHtml(r.tournament)}</td><td>${r.record?.wins || 0}-${r.record?.losses || 0}-${r.record?.ties || 0}</td></tr>`).join('') + '</tbody></table>';
}

function openArchetype(name) {
  document.querySelector('[data-tab="archetype"]').click();
  renderArchetype(name);
}

$('apply').onclick = applyFilters;
$('refresh').onclick = () => loadShared(true);
setupTabs();
loadShared(false);
