-- Shared/public format-calendar persistence.
-- This is deliberately separate from per-user snapshots and the legacy format registry tables.

create table if not exists public.ptcg_maintained_calendar_versions (
  id uuid primary key default gen_random_uuid(),
  version_number bigint generated by default as identity unique not null,
  status text not null default 'draft' check (status in ('draft','published','archived')),
  registry jsonb not null check (
    jsonb_typeof(registry) = 'object'
    and registry @> '{"schemaVersion":1,"kind":"user-maintained"}'::jsonb
  ),
  notes text not null default '',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  published_at timestamptz
);

create unique index if not exists ptcg_maintained_calendar_one_published
  on public.ptcg_maintained_calendar_versions ((status))
  where status = 'published';

alter table public.ptcg_maintained_calendar_versions enable row level security;

drop policy if exists maintained_calendar_public_read on public.ptcg_maintained_calendar_versions;
create policy maintained_calendar_public_read
  on public.ptcg_maintained_calendar_versions
  for select
  to anon, authenticated
  using (
    status = 'published'
    or exists (
      select 1 from public.ptcg_admins a
      where a.user_id = (select auth.uid())
    )
  );

drop policy if exists maintained_calendar_admin_insert_draft on public.ptcg_maintained_calendar_versions;
create policy maintained_calendar_admin_insert_draft
  on public.ptcg_maintained_calendar_versions
  for insert
  to authenticated
  with check (
    status = 'draft'
    and created_by = (select auth.uid())
    and exists (
      select 1 from public.ptcg_admins a
      where a.user_id = (select auth.uid())
    )
  );

drop policy if exists maintained_calendar_admin_update_draft on public.ptcg_maintained_calendar_versions;
create policy maintained_calendar_admin_update_draft
  on public.ptcg_maintained_calendar_versions
  for update
  to authenticated
  using (
    status = 'draft'
    and exists (
      select 1 from public.ptcg_admins a
      where a.user_id = (select auth.uid())
    )
  )
  with check (
    status = 'draft'
    and created_by = (select auth.uid())
    and exists (
      select 1 from public.ptcg_admins a
      where a.user_id = (select auth.uid())
    )
  );

create or replace function public.ptcg_publish_maintained_calendar(p_id uuid)
returns public.ptcg_maintained_calendar_versions
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  result public.ptcg_maintained_calendar_versions;
begin
  if (select auth.uid()) is null or not exists (
    select 1 from public.ptcg_admins a
    where a.user_id = (select auth.uid())
  ) then
    raise exception 'PTCG admin access required' using errcode = '42501';
  end if;

  select * into result
  from public.ptcg_maintained_calendar_versions
  where id = p_id
  for update;

  if not found then
    raise exception 'Maintained calendar draft not found' using errcode = 'P0002';
  end if;

  if result.status <> 'draft' then
    raise exception 'Only a draft calendar can be published' using errcode = '22023';
  end if;

  if jsonb_typeof(result.registry) <> 'object'
     or not (result.registry @> '{"schemaVersion":1,"kind":"user-maintained"}'::jsonb) then
    raise exception 'Invalid maintained calendar registry shape' using errcode = '22023';
  end if;

  update public.ptcg_maintained_calendar_versions
  set status = 'archived'
  where status = 'published';

  update public.ptcg_maintained_calendar_versions
  set status = 'published', published_at = now()
  where id = p_id
  returning * into result;

  return result;
end;
$$;

revoke all on function public.ptcg_publish_maintained_calendar(uuid) from public;
grant execute on function public.ptcg_publish_maintained_calendar(uuid) to authenticated;

-- Seed the shared live row from the checked-in maintained-calendar fallback.
insert into public.ptcg_maintained_calendar_versions (status, registry, notes, published_at)
select 'published', $$
{
  "schemaVersion": 1,
  "kind": "user-maintained",
  "revision": "user-calendar-2026-09-08.1",
  "scope": "tpci-international-standard",
  "sources": {
    "user-2026-09-08": {
      "title": "Project owner supplied current format and 30C legality dates on 8 September 2026",
      "authority": "user-maintained",
      "note": "Not independently verified. Current H–J; TEF through PBL. 30C Online 15 September, IRL 24 September. Later sets and rotation unknown."
    }
  },
  "baseline": {
    "id": "standard-h-j-tef-pbl",
    "asOf": "2026-09-08",
    "regulationMarks": ["H", "I", "J"],
    "earliestSet": "TEF",
    "latestSets": ["PBL"],
    "source": "user-2026-09-08"
  },
  "coverage": {
    "catalog": {"complete": false, "note": "Maintained format boundaries; exhaustive historical set roster/release dates not supplied."},
    "online": {"complete": false, "note": "Current baseline and known additions only; no historical rotation date inferred."},
    "irl": {"complete": false, "note": "Current baseline and known additions only; no historical rotation date inferred."}
  },
  "sets": [
    {
      "id": "30C",
      "name": "30th Celebration",
      "release": {
        "value": null,
        "status": "announced",
        "sources": ["user-2026-09-08"],
        "convention": "calendar-day-inclusive",
        "note": "Release date not supplied; never copied from a legality date."
      },
      "marks": {
        "value": null,
        "status": "unknown",
        "sources": [],
        "note": "Card-level mark inventory not supplied; ordinary addition retains the maintained rotation boundary."
      },
      "legality": {
        "online": {
          "value": "2026-09-15",
          "status": "confirmed",
          "sources": ["user-2026-09-08"],
          "convention": "calendar-day-inclusive"
        },
        "irl": {
          "value": "2026-09-24",
          "status": "confirmed",
          "sources": ["user-2026-09-08"],
          "convention": "calendar-day-inclusive"
        }
      },
      "rotation": null
    }
  ],
  "rotations": {"online": [], "irl": []},
  "unknowns": [
    "30C release date",
    "Next rotation date and lower boundary",
    "Set releases after 30C"
  ]
}
$$::jsonb, 'Bootstrap copy of data/formats/maintained-calendar.json', now()
where not exists (
  select 1 from public.ptcg_maintained_calendar_versions where status = 'published'
);
