(function(global){
  'use strict';
  const providerNames={google:'Google'};
  const els=()=>({status:[...document.querySelectorAll('[data-ptcg-auth-status]')],name:[...document.querySelectorAll('[data-ptcg-auth-name]')],provider:[...document.querySelectorAll('[data-ptcg-auth-provider-label]')],signedIn:[...document.querySelectorAll('[data-ptcg-auth-signed-in]')],signedOut:[...document.querySelectorAll('[data-ptcg-auth-signed-out]')],message:[...document.querySelectorAll('[data-ptcg-auth-message]')]});
  function setMessage(text,isError){for(const el of els().message){el.textContent=text||'';el.classList.toggle('is-error',!!isError)}}
  function appRoot(){const declared=document.body?.dataset?.appRoot||'.';return new URL(declared.endsWith('/')?declared:`${declared}/`,document.baseURI).href}
  async function render(){if(!global.PTCGCloud)return;const [user,status]=await Promise.all([global.PTCGCloud.getUser(),global.PTCGCloud.providerStatus?.()||{}]);const e=els(),label=global.PTCGCloud.userLabel(user),provider=global.PTCGCloud.providerLabel(user);for(const el of e.status){el.textContent=user?label:'Not signed in';el.dataset.signedIn=user?'true':'false'}for(const el of e.name)el.textContent=user?label:'Guest';for(const el of e.provider)el.textContent=user?(provider?`Signed in with ${provider}`:'Signed in'):'Not signed in';for(const el of e.signedIn)el.hidden=!user;for(const el of e.signedOut)el.hidden=!!user;document.querySelectorAll('[data-ptcg-auth-provider]').forEach(btn=>{const enabled=!!status[btn.dataset.ptcgAuthProvider];btn.disabled=!enabled;btn.title=enabled?'':`${providerNames[btn.dataset.ptcgAuthProvider]||'This provider'} is not configured yet`;btn.setAttribute('aria-disabled',enabled?'false':'true')});if(!user&&!status.google)setMessage('Google sign-in is temporarily unavailable.',false)}
  async function signIn(provider,button){setMessage('');if(button)button.disabled=true;try{await global.PTCGCloud.signInWithProvider(provider,appRoot())}catch(error){setMessage(error?.message||'Could not sign in with Google.',true);await render();if(button)button.disabled=false}}
  async function signOut(button){setMessage('');if(button)button.disabled=true;try{await global.PTCGCloud.signOut();await render();setMessage('Signed out.')}catch(error){setMessage(error?.message||'Could not sign out.',true)}finally{if(button)button.disabled=false}}
  document.addEventListener('click',event=>{const providerButton=event.target.closest('[data-ptcg-auth-provider]');if(providerButton){event.preventDefault();if(!providerButton.disabled)signIn(providerButton.dataset.ptcgAuthProvider,providerButton);return}const out=event.target.closest('[data-ptcg-auth-signout]');if(out){event.preventDefault();signOut(out)}});
  async function init(){if(!global.PTCGCloud)return;await render();try{const result=await global.PTCGCloud.onAuthStateChange(()=>{render();window.dispatchEvent(new CustomEvent('ptcg:auth-change'))});global.__ptcgAuthSubscription=result?.data?.subscription||null}catch(error){console.warn('Auth state listener unavailable',error)}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();global.PTCGAuthUI={render};
})(window);
