(() => {
  'use strict';
  const DAY=86400000;
  const DEFAULT_FORMULA={versionKey:'blended-v2',versionNumber:2,irlStartWeight:0.70,irlFloor:0.30,irlDecayPerDay:0.02,previousFormatCap:0.25,transitionPolicy:'format-aware-v2'};
  const clamp=(min,max,value)=>Math.min(max,Math.max(min,value));
  function startOfLocalDay(value){const d=new Date(value);return Number.isNaN(d.getTime())?null:new Date(d.getFullYear(),d.getMonth(),d.getDate())}
  function isoWeekKey(value){const date=new Date(value),utc=new Date(Date.UTC(date.getUTCFullYear(),date.getUTCMonth(),date.getUTCDate())),day=utc.getUTCDay()||7;utc.setUTCDate(utc.getUTCDate()+4-day);const start=new Date(Date.UTC(utc.getUTCFullYear(),0,1)),week=Math.ceil((((utc-start)/DAY)+1)/7);return `${utc.getUTCFullYear()}-W${String(week).padStart(2,'0')}`}
  function formulaFromCore(core){return {...DEFAULT_FORMULA,...(core?.config?.formula||{})}}
  function weightsForDays(value,formula=DEFAULT_FORMULA){const days=Math.max(0,Number(value||0)),start=clamp(0,1,Number(formula.irlStartWeight??0.70)),floor=clamp(0,start,Number(formula.irlFloor??0.30)),decay=Math.max(0,Number(formula.irlDecayPerDay??0.02)),irl=clamp(floor,start,start-decay*days);return {irl,online:1-irl}}
  function normaliseRows(rows,source){if(globalThis.PTCGMetaField?.normalizeRows)return globalThis.PTCGMetaField.normalizeRows(rows,{source});const clean=(Array.isArray(rows)?rows:[]).map(row=>({name:String(row?.name||'').trim(),share:Math.max(0,Number(row?.share||0)),source})).filter(row=>row.name&&row.name!=='Other'&&row.name!=='Unknown'&&row.share>0),total=clean.reduce((sum,row)=>sum+row.share,0);return total?clean.map(row=>({...row,share:row.share/total})):[]}
  function mergeRows(irlRows,onlineRows,configuredWeights){const irl=normaliseRows(irlRows,'irl'),online=normaliseRows(onlineRows,'online');if(!irl.length&&!online.length)return {rows:[],weights:{irl:0,online:0}};if(!irl.length)return {rows:online.map(row=>({...row,source:'blend'})),weights:{irl:0,online:1}};if(!online.length)return {rows:[],weights:{irl:0,online:0}};const weights=configuredWeights||{irl:0.5,online:0.5},map=new Map();for(const row of irl)map.set(row.name,(map.get(row.name)||0)+row.share*weights.irl);for(const row of online)map.set(row.name,(map.get(row.name)||0)+row.share*weights.online);const total=[...map.values()].reduce((sum,value)=>sum+value,0),rows=[...map.entries()].map(([name,value])=>({name,share:total?value/total:0,source:'blend'})).filter(row=>row.share>0).sort((a,b)=>b.share-a.share||a.name.localeCompare(b.name));return {rows,weights}}
  function aggregateDecks(events){const counts=new Map();for(const event of events||[])for(const deck of event.decks||event.archetypes||[]){const name=String(deck?.name||'').trim();if(!name||name==='Other'||name==='Unknown')continue;counts.set(name,(counts.get(name)||0)+Number(deck.entries||0))}const total=[...counts.values()].reduce((sum,value)=>sum+value,0);return [...counts.entries()].map(([name,entries])=>({name,share:total?entries/total:0}))}
  function latestWeekend(events){const valid=[...(events||[])].filter(event=>Number.isFinite(new Date(event?.date).getTime())).sort((a,b)=>new Date(b.date)-new Date(a.date));if(!valid.length)return[];const week=isoWeekKey(valid[0].date);return valid.filter(event=>isoWeekKey(event.date)===week)}
  function weekendFinalDay(events,core){const cutoff=new Date(core?.online?.majorWeekend?.cutoff).getTime();if(Number.isFinite(cutoff))return startOfLocalDay(new Date(cutoff-DAY));const weekend=latestWeekend(events),latest=weekend.length?Math.max(...weekend.map(event=>new Date(event.date).getTime())):NaN;if(!Number.isFinite(latest))return null;const date=new Date(latest),day=date.getUTCDay()||7,sunday=new Date(Date.UTC(date.getUTCFullYear(),date.getUTCMonth(),date.getUTCDate()));sunday.setUTCDate(sunday.getUTCDate()+(7-day));return startOfLocalDay(sunday)}
  function daysFromWeekend(events,core,nowValue){const finalDay=weekendFinalDay(events,core),now=startOfLocalDay(nowValue||new Date());return {finalDay,days:finalDay&&now?Math.max(0,Math.floor((now-finalDay)/DAY)):null}}
  function onlineRowsFromCore(core){return (core?.online?.scopes?.['since-major']?.decks||[]).map(deck=>({name:deck.name,share:Number(deck.share||0)/100}))}
  function formatId(value){return value?.id||value?.format||null}
  function candidateFromCore(core){const onlineFormat=formatId(core?.config?.onlineFormat)||core?.online?.format||core?.format||null,currentIrlFormat=core?.irl?.format||formatId(core?.config?.irlFormat),currentEvents=latestWeekend(core?.irl?.events||[]);if(currentEvents.length&&currentIrlFormat===onlineFormat)return{kind:'current',format:currentIrlFormat,events:currentEvents};if(currentEvents.length&&currentIrlFormat&&currentIrlFormat!==onlineFormat)return{kind:'previous',format:currentIrlFormat,events:currentEvents};const previous=core?.irl?.previous,previousEvents=latestWeekend(previous?.events||[]),previousOnline=formatId(core?.config?.previousOnlineFormat);if(previousEvents.length&&(!previousOnline||previous?.format===previousOnline))return{kind:'previous',format:previous?.format||previousOnline,events:previousEvents};return{kind:'none',format:null,events:[]}}
  function unavailable(core,reason,options={}){const formula=formulaFromCore(core);return{available:false,reason,rows:[],weights:{irl:0,online:0},configuredWeights:{irl:0,online:0},daysSinceMajor:null,majorDate:null,majorFinalDate:null,irlScope:'latest-weekend',onlineScope:'since-major',minOnlinePlayers:50,formula,format:formatId(core?.config?.onlineFormat)||core?.online?.format||core?.format||null,transitionState:'unavailable',earlyFormat:false,generatedAt:core?.online?.generatedAt||null,...options}}
  function currentFromCore(core,options={}){const online=onlineRowsFromCore(core),format=formatId(core?.config?.onlineFormat)||core?.online?.format||core?.format||null,formula=formulaFromCore(core);if(!online.length)return unavailable(core,'Waiting for a qualifying 50+ player Online event in the current format.');const candidate=candidateFromCore(core),rotation=!!core?.config?.onlineFormat?.isRotationStart,{finalDay,days}=daysFromWeekend(candidate.events,core,options.now||new Date());let configuredWeights={irl:0,online:1},transitionState='online-only',earlyFormat=false;if(candidate.kind==='current'&&candidate.events.length){configuredWeights=weightsForDays(days??0,formula);transitionState='current-format-major';}else if(candidate.kind==='previous'&&candidate.events.length&&!rotation){const normal=weightsForDays(days??0,formula),cap=clamp(0,1,Number(formula.previousFormatCap??0.25)),irl=Math.min(normal.irl,cap);configuredWeights={irl,online:1-irl};transitionState='previous-format-prior';earlyFormat=true;}else if(rotation){transitionState='rotation-online-only';earlyFormat=true;}else{earlyFormat=true;}const irlRows=configuredWeights.irl>0?aggregateDecks(candidate.events):[],blended=mergeRows(irlRows,online,configuredWeights);if(!blended.rows.length)return unavailable(core,'Blended is unavailable because current-format Online evidence cannot be combined safely.');const dates=candidate.events.map(event=>startOfLocalDay(event?.date)).filter(Boolean).sort((a,b)=>b-a),majorDate=dates[0]||null;return{available:true,reason:'',rows:blended.rows,weights:blended.weights,configuredWeights,daysSinceMajor:days,majorDate:majorDate?majorDate.toISOString().slice(0,10):null,majorFinalDate:finalDay?finalDay.toISOString().slice(0,10):null,irlScope:'latest-weekend',onlineScope:'since-major',minOnlinePlayers:50,formula,format,irlFormat:candidate.format,transitionState,earlyFormat,generatedAt:core?.online?.generatedAt||null}}
  function currentFromMeta(meta,options={}){const core=globalThis.window?.MetaRelease?.core?.();if(core)return currentFromCore(core,options);if(!meta?.fieldRows||!meta?.irlEvents)return unavailable(null,'Blended Meta is not ready.');const events=meta.irlEvents('latest-weekend')||[],online=meta.fieldRows('online',{scope:'since-major',minPlayers:50,recency:'equal'});if(!online.length)return unavailable(null,'Waiting for a qualifying 50+ player Online event in the current format.');const {finalDay,days}=daysFromWeekend(events,null,options.now||new Date()),weights=weightsForDays(days??0,DEFAULT_FORMULA),blended=mergeRows(meta.fieldRows('irl',{scope:'latest-weekend'}),online,weights);return{available:!!blended.rows.length,reason:blended.rows.length?'':'Blended Meta is not ready.',rows:blended.rows,weights:blended.weights,configuredWeights:weights,daysSinceMajor:days,majorFinalDate:finalDay?finalDay.toISOString().slice(0,10):null,irlScope:'latest-weekend',onlineScope:'since-major',minOnlinePlayers:50,formula:DEFAULT_FORMULA,format:null,transitionState:'legacy-fallback',earlyFormat:false}}
  window.PTCGMetaBlend={currentFromMeta,currentFromCore,mergeRows,weightsForDays,policy:{defaults:{...DEFAULT_FORMULA}}};
})();
