(() => {
  'use strict';
  const DAY=86400000,IRL_MAX=0.70,IRL_MIN=0.30,IRL_DECAY_PER_DAY=0.02;
  const clamp=(min,max,value)=>Math.min(max,Math.max(min,value));
  function startOfLocalDay(value){const d=new Date(value);return Number.isNaN(d.getTime())?null:new Date(d.getFullYear(),d.getMonth(),d.getDate())}
  function isoWeekKey(value){const date=new Date(value),utc=new Date(Date.UTC(date.getUTCFullYear(),date.getUTCMonth(),date.getUTCDate())),day=utc.getUTCDay()||7;utc.setUTCDate(utc.getUTCDate()+4-day);const start=new Date(Date.UTC(utc.getUTCFullYear(),0,1)),week=Math.ceil((((utc-start)/DAY)+1)/7);return `${utc.getUTCFullYear()}-W${String(week).padStart(2,'0')}`}
  function weightsForDays(value){const days=Math.max(0,Number(value||0)),irl=clamp(IRL_MIN,IRL_MAX,IRL_MAX-IRL_DECAY_PER_DAY*days);return {irl,online:1-irl}}
  function normaliseRows(rows,source){const clean=(Array.isArray(rows)?rows:[]).map(row=>({name:String(row?.name||'').trim(),share:Math.max(0,Number(row?.share||0)),source})).filter(row=>row.name&&row.share>0),total=clean.reduce((sum,row)=>sum+row.share,0);return total?clean.map(row=>({...row,share:row.share/total})):[]}
  function mergeRows(irlRows,onlineRows,configuredWeights){const irl=normaliseRows(irlRows,'irl'),online=normaliseRows(onlineRows,'online');if(!irl.length&&!online.length)return {rows:[],weights:{irl:0,online:0}};if(!irl.length)return {rows:online.map(row=>({...row,source:'blend'})),weights:{irl:0,online:1}};if(!online.length)return {rows:irl.map(row=>({...row,source:'blend'})),weights:{irl:1,online:0}};const weights=configuredWeights||{irl:0.5,online:0.5},map=new Map();for(const row of irl)map.set(row.name,(map.get(row.name)||0)+row.share*weights.irl);for(const row of online)map.set(row.name,(map.get(row.name)||0)+row.share*weights.online);const total=[...map.values()].reduce((sum,value)=>sum+value,0),rows=[...map.entries()].map(([name,value])=>({name,share:total?value/total:0,source:'blend'})).filter(row=>row.share>0).sort((a,b)=>b.share-a.share||a.name.localeCompare(b.name));return {rows,weights}}
  function aggregateDecks(events){const counts=new Map();for(const event of events||[])for(const deck of event.decks||event.archetypes||[]){const name=String(deck?.name||'').trim();if(!name||name==='Other'||name==='Unknown')continue;counts.set(name,(counts.get(name)||0)+Number(deck.entries||0))}const total=[...counts.values()].reduce((sum,value)=>sum+value,0);return [...counts.entries()].map(([name,entries])=>({name,share:total?entries/total:0}))}
  function result(irlRows,onlineRows,events,options={}){const dates=(events||[]).map(event=>startOfLocalDay(event?.date)).filter(Boolean).sort((a,b)=>b-a),majorDate=dates[0]||null,now=startOfLocalDay(options.now||new Date()),daysSinceMajor=majorDate&&now?Math.max(0,Math.floor((now-majorDate)/DAY)):null,configuredWeights=daysSinceMajor==null?{irl:0.5,online:0.5}:weightsForDays(daysSinceMajor),blended=mergeRows(irlRows,onlineRows,configuredWeights);return {rows:blended.rows,weights:blended.weights,configuredWeights,daysSinceMajor,majorDate:majorDate?majorDate.toISOString().slice(0,10):null,irlScope:'latest-weekend',onlineScope:'since-major',minOnlinePlayers:50}}
  function currentFromMeta(meta,options={}){if(!meta?.fieldRows||!meta?.irlEvents)return result([],[],[],options);const events=meta.irlEvents('latest-weekend')||[];return result(meta.fieldRows('irl',{scope:'latest-weekend'}),meta.fieldRows('online',{scope:'since-major',minPlayers:50,recency:'equal'}),events,options)}
  function currentFromCore(core,options={}){const events=[...(core?.irl?.events||[])].filter(event=>Number.isFinite(new Date(event.date).getTime())).sort((a,b)=>new Date(b.date)-new Date(a.date)),latestWeek=events.length?isoWeekKey(events[0].date):'',latest=events.filter(event=>isoWeekKey(event.date)===latestWeek),online=(core?.online?.scopes?.['since-major']?.decks||[]).map(deck=>({name:deck.name,share:Number(deck.share||0)/100}));return result(aggregateDecks(latest),online,latest,options)}
  window.PTCGMetaBlend={currentFromMeta,currentFromCore,mergeRows,weightsForDays,policy:{irlMax:IRL_MAX,irlMin:IRL_MIN,irlDecayPerDay:IRL_DECAY_PER_DAY}};
})();
