(() => {
  'use strict';
  const DAY=86400000;
  const DEFAULT_FORMULA=Object.freeze({versionKey:'blended-v2',versionNumber:2,irlStartWeight:.70,irlDecayPerDay:.02,irlFloor:.30,previousFormatCap:.25,transitionPolicy:'format-aware-v2'});
  const clamp=(min,max,value)=>Math.min(max,Math.max(min,Number(value)||0));
  function startOfLocalDay(value){const d=new Date(value);return Number.isNaN(d.getTime())?null:new Date(d.getFullYear(),d.getMonth(),d.getDate())}
  function isoWeekKey(value){const date=new Date(value),utc=new Date(Date.UTC(date.getUTCFullYear(),date.getUTCMonth(),date.getUTCDate())),day=utc.getUTCDay()||7;utc.setUTCDate(utc.getUTCDate()+4-day);const start=new Date(Date.UTC(utc.getUTCFullYear(),0,1)),week=Math.ceil((((utc-start)/DAY)+1)/7);return `${utc.getUTCFullYear()}-W${String(week).padStart(2,'0')}`}
  function liveRuntime(){return globalThis.PTCGFormatRuntime?.current?.()||null}
  function formulaFromCore(core){const live=liveRuntime()?.formula;if(live)return {...DEFAULT_FORMULA,...live};return {...DEFAULT_FORMULA,...(core?.config?.formula||{})}}
  function weightsForDays(value,formula=DEFAULT_FORMULA){const days=Math.max(0,Number(value||0)),start=clamp(0,1,formula.irlStartWeight),floor=clamp(0,start,formula.irlFloor),decay=clamp(0,1,formula.irlDecayPerDay),irl=clamp(floor,start,start-decay*days);return {irl,online:1-irl}}
  function normaliseRows(rows,source){if(globalThis.PTCGMetaField?.normalizeRows)return globalThis.PTCGMetaField.normalizeRows(rows,{source});const clean=(Array.isArray(rows)?rows:[]).map(row=>({name:String(row?.name||'').trim(),share:Math.max(0,Number(row?.share||0)),source})).filter(row=>row.name&&row.name!=='Other'&&row.name!=='Unknown'&&row.share>0),total=clean.reduce((sum,row)=>sum+row.share,0);return total?clean.map(row=>({...row,share:row.share/total})):[]}
  function mergeRows(irlRows,onlineRows,configuredWeights){const irl=normaliseRows(irlRows,'irl'),online=normaliseRows(onlineRows,'online');if(!online.length)return {rows:[],weights:{irl:0,online:0}};if(!irl.length||!Number(configuredWeights?.irl))return {rows:online.map(row=>({...row,source:'blend'})),weights:{irl:0,online:1}};const weights=configuredWeights||{irl:0,online:1},map=new Map();for(const row of irl)map.set(row.name,(map.get(row.name)||0)+row.share*weights.irl);for(const row of online)map.set(row.name,(map.get(row.name)||0)+row.share*weights.online);const total=[...map.values()].reduce((sum,value)=>sum+value,0),rows=[...map.entries()].map(([name,value])=>({name,share:total?value/total:0,source:'blend'})).filter(row=>row.share>0).sort((a,b)=>b.share-a.share||a.name.localeCompare(b.name));return {rows,weights}}
  function aggregateDecks(events){const counts=new Map();for(const event of events||[])for(const deck of event.decks||event.archetypes||[]){const name=String(deck?.name||'').trim();if(!name||name==='Other'||name==='Unknown')continue;counts.set(name,(counts.get(name)||0)+Number(deck.entries||0))}const total=[...counts.values()].reduce((sum,value)=>sum+value,0);return [...counts.entries()].map(([name,entries])=>({name,share:total?entries/total:0}))}
  function latestWeekend(events){const valid=[...(events||[])].filter(event=>Number.isFinite(new Date(event?.date).getTime())).sort((a,b)=>new Date(b.date)-new Date(a.date));if(!valid.length)return[];const key=isoWeekKey(valid[0].date);return valid.filter(event=>isoWeekKey(event.date)===key)}
  function weekendFinalDay(core,events){const cutoff=new Date(core?.online?.majorWeekend?.cutoff).getTime();if(Number.isFinite(cutoff))return new Date(cutoff-DAY);const times=(events||[]).map(event=>new Date(event.endDate||event.date).getTime()).filter(Number.isFinite);return times.length?new Date(Math.max(...times)):null}
  function daysSince(finalDate,now){const a=startOfLocalDay(finalDate),b=startOfLocalDay(now);return a&&b?Math.max(0,Math.floor((b-a)/DAY)):null}
  function onlineRows(core){return (core?.online?.scopes?.['since-major']?.decks||[]).map(deck=>({name:deck.name,share:Number(deck.share||0)/100}))}
  function formatIds(core){const runtime=liveRuntime(),online=runtime?.online?.id||core?.config?.onlineFormat?.id||core?.online?.format||core?.format||null,irl=runtime?.irl?.id||core?.config?.irlFormat?.id||core?.irl?.format||null,coreOnline=core?.online?.format||core?.config?.onlineFormat?.id||core?.format||null;return{online,irl,coreOnline}}
  function chooseIrl(core,onlineFormat){const currentEvents=latestWeekend(core?.irl?.events||[]),currentFormat=core?.irl?.format||core?.config?.irlFormat?.id||null;if(currentEvents.length&&currentFormat===onlineFormat)return{kind:'current-format-major',formatId:currentFormat,events:currentEvents};if(currentEvents.length&&currentFormat!==onlineFormat)return{kind:'previous-format-prior',formatId:currentFormat,events:currentEvents};const previous=core?.irl?.previous,prior=latestWeekend(previous?.events||[]);if(prior.length)return{kind:'previous-format-prior',formatId:previous?.format||null,events:prior};return{kind:'none',formatId:null,events:[]}}
  function unavailable(core,reason,extra={}){const ids=formatIds(core),formula=formulaFromCore(core);return{available:false,reason,rows:[],weights:{irl:0,online:0},configuredWeights:{irl:0,online:0},daysSinceMajor:null,majorDate:null,majorFinalDate:null,irlScope:'latest-weekend',onlineScope:'since-major',minOnlinePlayers:50,formula,format:ids.online,irlFormat:ids.irl,transitionState:'unavailable',earlyFormat:false,generatedAt:core?.online?.generatedAt||null,...extra}}
  function currentFromCore(core,options={}){
    if(!core)return unavailable(core,'Meta data is unavailable.');
    const ids=formatIds(core),formula=formulaFromCore(core);
    if(ids.online&&ids.coreOnline&&ids.online!==ids.coreOnline)return unavailable(core,`Waiting for qualifying 50+ player Online data for ${ids.online}.`,{format:ids.online,formula});
    const online=onlineRows(core);if(!normaliseRows(online,'online').length)return unavailable(core,`Waiting for a qualifying 50+ player Online event in ${ids.online||'the current format'}.`,{format:ids.online,formula});
    const candidate=chooseIrl(core,ids.online),finalDate=weekendFinalDay(core,candidate.events),now=options.now||new Date(),elapsed=finalDate?daysSince(finalDate,now):null,rotation=!!(liveRuntime()?.online?.isRotationStart||core?.config?.onlineFormat?.isRotationStart);
    let transitionState='online-only',configuredWeights={irl:0,online:1};
    if(candidate.kind==='current-format-major'){transitionState='current-format-major';configuredWeights=weightsForDays(elapsed??0,formula)}
    else if(candidate.kind==='previous-format-prior'&&!rotation){transitionState='previous-format-prior';const normal=weightsForDays(elapsed??0,formula),irl=Math.min(normal.irl,clamp(0,1,formula.previousFormatCap??.25));configuredWeights={irl,online:1-irl}}
    else if(rotation)transitionState='rotation-online-only';
    const irl=configuredWeights.irl?aggregateDecks(candidate.events):[],blended=mergeRows(irl,online,configuredWeights),majorDate=candidate.events.length?String(candidate.events[0].date||'').slice(0,10):null;
    return{available:true,reason:null,rows:blended.rows,weights:blended.weights,configuredWeights,daysSinceMajor:elapsed,majorDate,majorFinalDate:finalDate?finalDate.toISOString().slice(0,10):null,irlScope:'latest-weekend',onlineScope:'since-major',minOnlinePlayers:50,formula,format:ids.online,irlFormat:candidate.formatId||ids.irl,transitionState,earlyFormat:transitionState!=='current-format-major',generatedAt:core?.online?.generatedAt||null};
  }
  function currentFromMeta(meta,options={}){if(globalThis.MetaRelease?.core?.())return currentFromCore(globalThis.MetaRelease.core(),options);if(!meta?.fieldRows||!meta?.irlEvents)return unavailable(null,'Meta data is unavailable.');const events=meta.irlEvents('latest-weekend')||[],online=meta.fieldRows('online',{scope:'since-major',minPlayers:50,recency:'equal'});if(!normaliseRows(online,'online').length)return unavailable(null,'Waiting for a qualifying 50+ player Online event in the current format.');const final=events.length?new Date(Math.max(...events.map(e=>new Date(e.endDate||e.date).getTime()).filter(Number.isFinite))):null,elapsed=final?daysSince(final,options.now||new Date()):null,formula=liveRuntime()?.formula||DEFAULT_FORMULA,weights=events.length?weightsForDays(elapsed??0,formula):{irl:0,online:1},blended=mergeRows(meta.fieldRows('irl',{scope:'latest-weekend'}),online,weights);return{available:true,rows:blended.rows,weights:blended.weights,configuredWeights:weights,daysSinceMajor:elapsed,majorDate:events[0]?.date||null,majorFinalDate:final?.toISOString().slice(0,10)||null,irlScope:'latest-weekend',onlineScope:'since-major',minOnlinePlayers:50,formula,format:liveRuntime()?.online?.id||null,irlFormat:liveRuntime()?.irl?.id||null,transitionState:events.length?'current-format-major':'online-only',earlyFormat:!events.length,generatedAt:null}}
  globalThis.PTCGMetaBlend={currentFromMeta,currentFromCore,mergeRows,weightsForDays,policy:DEFAULT_FORMULA};
})();
